//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareMonkeys.WorkHub.Modules.Projects.Properties {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Language {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		public Language() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftwareMonkeys.WorkHub.Modules.Projects.Properties.Language", typeof(Language).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Active.
		/// </summary>
		public static string Active {
			get {
				return ResourceManager.GetString("Active", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Active/Public Projects.
		/// </summary>
		public static string ActivePublicProjects {
			get {
				return ResourceManager.GetString("ActivePublicProjects", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to All Projects.
		/// </summary>
		public static string AllProjects {
			get {
				return ResourceManager.GetString("AllProjects", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Archived.
		/// </summary>
		public static string Archived {
			get {
				return ResourceManager.GetString("Archived", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to (asc).
		/// </summary>
		public static string Asc {
			get {
				return ResourceManager.GetString("Asc", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Company Name.
		/// </summary>
		public static string CompanyName {
			get {
				return ResourceManager.GetString("CompanyName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Are you sure you want to cancel creating this project?.
		/// </summary>
		public static string ConfirmCancelCreateProject {
			get {
				return ResourceManager.GetString("ConfirmCancelCreateProject", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Are you sure you wish to delete this project and all related data?.
		/// </summary>
		public static string ConfirmDeleteProject {
			get {
				return ResourceManager.GetString("ConfirmDeleteProject", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Contributors.
		/// </summary>
		public static string Contributors {
			get {
				return ResourceManager.GetString("Contributors", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Create.
		/// </summary>
		public static string Create {
			get {
				return ResourceManager.GetString("Create", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Create Project.
		/// </summary>
		public static string CreateProject {
			get {
				return ResourceManager.GetString("CreateProject", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Enter the new project details in the form below..
		/// </summary>
		public static string CreateProjectIntro {
			get {
				return ResourceManager.GetString("CreateProjectIntro", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Current.
		/// </summary>
		public static string Current {
			get {
				return ResourceManager.GetString("Current", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Current Version.
		/// </summary>
		public static string CurrentVersion {
			get {
				return ResourceManager.GetString("CurrentVersion", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Delete.
		/// </summary>
		public static string Delete {
			get {
				return ResourceManager.GetString("Delete", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Delete this project.
		/// </summary>
		public static string DeleteProjectToolTip {
			get {
				return ResourceManager.GetString("DeleteProjectToolTip", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to &apos;Demand&apos; Votes Balance.
		/// </summary>
		public static string DemandVotesBalance {
			get {
				return ResourceManager.GetString("DemandVotesBalance", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to (desc).
		/// </summary>
		public static string Desc {
			get {
				return ResourceManager.GetString("Desc", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Edit.
		/// </summary>
		public static string Edit {
			get {
				return ResourceManager.GetString("Edit", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Edit Project.
		/// </summary>
		public static string EditProject {
			get {
				return ResourceManager.GetString("EditProject", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Edit the project details in the form below..
		/// </summary>
		public static string EditProjectIntro {
			get {
				return ResourceManager.GetString("EditProjectIntro", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Edit this project.
		/// </summary>
		public static string EditProjectToolTip {
			get {
				return ResourceManager.GetString("EditProjectToolTip", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Effective.
		/// </summary>
		public static string Effective {
			get {
				return ResourceManager.GetString("Effective", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to &apos;Effective&apos; Votes Balance.
		/// </summary>
		public static string EffectiveVotesBalance {
			get {
				return ResourceManager.GetString("EffectiveVotesBalance", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to external link.
		/// </summary>
		public static string ExternalLink {
			get {
				return ResourceManager.GetString("ExternalLink", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Guide.
		/// </summary>
		public static string Guide {
			get {
				return ResourceManager.GetString("Guide", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Home.
		/// </summary>
		public static string Home {
			get {
				return ResourceManager.GetString("Home", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ID.
		/// </summary>
		public static string ID {
			get {
				return ResourceManager.GetString("ID", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Inactive.
		/// </summary>
		public static string Inactive {
			get {
				return ResourceManager.GetString("Inactive", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Index.
		/// </summary>
		public static string Index {
			get {
				return ResourceManager.GetString("Index", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Keywords.
		/// </summary>
		public static string Keywords {
			get {
				return ResourceManager.GetString("Keywords", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Manage Projects.
		/// </summary>
		public static string ManageProjects {
			get {
				return ResourceManager.GetString("ManageProjects", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Create and manage projects in the index below..
		/// </summary>
		public static string ManageProjectsIntro {
			get {
				return ResourceManager.GetString("ManageProjectsIntro", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Manager.
		/// </summary>
		public static string Manager {
			get {
				return ResourceManager.GetString("Manager", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Managers.
		/// </summary>
		public static string Managers {
			get {
				return ResourceManager.GetString("Managers", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to More Information.
		/// </summary>
		public static string MoreInformation {
			get {
				return ResourceManager.GetString("MoreInformation", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to N/A.
		/// </summary>
		public static string NA {
			get {
				return ResourceManager.GetString("NA", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Name.
		/// </summary>
		public static string Name {
			get {
				return ResourceManager.GetString("Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Needed.
		/// </summary>
		public static string Needed {
			get {
				return ResourceManager.GetString("Needed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to New Project Details.
		/// </summary>
		public static string NewProjectDetails {
			get {
				return ResourceManager.GetString("NewProjectDetails", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No projects found..
		/// </summary>
		public static string NoProjects {
			get {
				return ResourceManager.GetString("NoProjects", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No project selected..
		/// </summary>
		public static string NoProjectSelected {
			get {
				return ResourceManager.GetString("NoProjectSelected", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No projects found..
		/// </summary>
		public static string NoProjectsFound {
			get {
				return ResourceManager.GetString("NoProjectsFound", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No summary has been provided for this project..
		/// </summary>
		public static string NoSummary {
			get {
				return ResourceManager.GetString("NoSummary", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Parent Projects.
		/// </summary>
		public static string ParentProjects {
			get {
				return ResourceManager.GetString("ParentProjects", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Please select a project from the &quot;Current Project&quot; list..
		/// </summary>
		public static string PleaseSelectProject {
			get {
				return ResourceManager.GetString("PleaseSelectProject", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Private.
		/// </summary>
		public static string Private {
			get {
				return ResourceManager.GetString("Private", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Project.
		/// </summary>
		public static string Project {
			get {
				return ResourceManager.GetString("Project", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The selected project was deleted successfully..
		/// </summary>
		public static string ProjectDeleted {
			get {
				return ResourceManager.GetString("ProjectDeleted", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Project Details.
		/// </summary>
		public static string ProjectDetails {
			get {
				return ResourceManager.GetString("ProjectDetails", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Project ID.
		/// </summary>
		public static string ProjectID {
			get {
				return ResourceManager.GetString("ProjectID", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Project Name.
		/// </summary>
		public static string ProjectName {
			get {
				return ResourceManager.GetString("ProjectName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Please enter a name for this project..
		/// </summary>
		public static string ProjectNameRequired {
			get {
				return ResourceManager.GetString("ProjectNameRequired", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The name of the project is in use, please try a different one..
		/// </summary>
		public static string ProjectNameTaken {
			get {
				return ResourceManager.GetString("ProjectNameTaken", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to You must select a project before you can do that. (Enable the Projects module if it&apos;s not already enabled.).
		/// </summary>
		public static string ProjectRequired {
			get {
				return ResourceManager.GetString("ProjectRequired", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Projects.
		/// </summary>
		public static string Projects {
			get {
				return ResourceManager.GetString("Projects", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The project was saved successfully..
		/// </summary>
		public static string ProjectSaved {
			get {
				return ResourceManager.GetString("ProjectSaved", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Project Summary.
		/// </summary>
		public static string ProjectSummary {
			get {
				return ResourceManager.GetString("ProjectSummary", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Projects XML.
		/// </summary>
		public static string ProjectsXml {
			get {
				return ResourceManager.GetString("ProjectsXml", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The links below display projects in XML format..
		/// </summary>
		public static string ProjectsXmlIntro {
			get {
				return ResourceManager.GetString("ProjectsXmlIntro", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Projects XML Pages.
		/// </summary>
		public static string ProjectsXmlPages {
			get {
				return ResourceManager.GetString("ProjectsXmlPages", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The project was updated successfully..
		/// </summary>
		public static string ProjectUpdated {
			get {
				return ResourceManager.GetString("ProjectUpdated", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Public.
		/// </summary>
		public static string Public {
			get {
				return ResourceManager.GetString("Public", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Related Projects.
		/// </summary>
		public static string RelatedProjects {
			get {
				return ResourceManager.GetString("RelatedProjects", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Save.
		/// </summary>
		public static string Save {
			get {
				return ResourceManager.GetString("Save", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Select Contributors.
		/// </summary>
		public static string SelectContributors {
			get {
				return ResourceManager.GetString("SelectContributors", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Select Managers.
		/// </summary>
		public static string SelectManagers {
			get {
				return ResourceManager.GetString("SelectManagers", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Select Projects.
		/// </summary>
		public static string SelectProjects {
			get {
				return ResourceManager.GetString("SelectProjects", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Status.
		/// </summary>
		public static string Status {
			get {
				return ResourceManager.GetString("Status", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Sub Projects.
		/// </summary>
		public static string SubProjects {
			get {
				return ResourceManager.GetString("SubProjects", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Summary.
		/// </summary>
		public static string Summary {
			get {
				return ResourceManager.GetString("Summary", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Total &apos;Demand&apos; Votes.
		/// </summary>
		public static string TotalDemandVotes {
			get {
				return ResourceManager.GetString("TotalDemandVotes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Total &apos;Effective&apos; Votes.
		/// </summary>
		public static string TotalEffectiveVotes {
			get {
				return ResourceManager.GetString("TotalEffectiveVotes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Total Votes.
		/// </summary>
		public static string TotalVotes {
			get {
				return ResourceManager.GetString("TotalVotes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Update.
		/// </summary>
		public static string Update {
			get {
				return ResourceManager.GetString("Update", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Version.
		/// </summary>
		public static string Version {
			get {
				return ResourceManager.GetString("Version", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to View.
		/// </summary>
		public static string View {
			get {
				return ResourceManager.GetString("View", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Visibility.
		/// </summary>
		public static string Visibility {
			get {
				return ResourceManager.GetString("Visibility", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Votes Balance.
		/// </summary>
		public static string VotesBalance {
			get {
				return ResourceManager.GetString("VotesBalance", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to XML.
		/// </summary>
		public static string Xml {
			get {
				return ResourceManager.GetString("Xml", resourceCulture);
			}
		}
	}
}
