/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\WebControls\CommandSelect.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Web.UI.WebControls;
using SoftwareMonkeys.WorkHub.Entities;
using SoftwareMonkeys.WorkHub.Web.Properties;

namespace SoftwareMonkeys.WorkHub.Web.WebControls
{
	/// <summary>
	/// Displays a drop down list for selecting a command (ie. a combination of "action" and "type").
	/// </summary>
	public class CommandSelect : WebControl
	{
		public DropDownList DropDownList = null;
		public Label TextLabel = null;
		
		private string commands = String.Empty;
		/// <summary>
		/// Gets/sets a commmands string. Example "User Index|Create User".
		/// </summary>
		public string Commands
		{
			get { return commands; }
			set { commands = value; }
		}
		
		public string SelectedCommand
		{
			get
			{
				return DropDownList.SelectedValue;
			}
			set
			{
				foreach (ListItem item in DropDownList.Items)
				{
					item.Selected = (item.Value == value);
				}
			}
		}
		
		private string text = Language.AndGoTo;
		/// <summary>
		/// Gets/sets the text displayed next to the drop down list.
		/// </summary>
		public string Text
		{
			get { return text; }
			set { text = value;
				TextLabel.Text = value;
				if (value.Trim() != String.Empty)
				    TextLabel.Text += " ";
			}
		}
				
		public CommandSelect()
		{
			CssClass = "CommandSelect";
		}
		
		protected override void OnInit(EventArgs e)
		{
			TextLabel = new Label();
			Controls.Add(TextLabel);
			TextLabel.Text = Text + " ";
			
			DropDownList = new DropDownList();
			Controls.Add(DropDownList);			
			
			string[] items = Commands.Split('|');
			
			foreach (String item in items)
			{				
				DropDownList.Items.Add(new ListItem(item, item));
			}
			
			base.OnInit(e);
		}
	}
}
