/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\WebControls\DeleteLink.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Web.UI.WebControls;
using System.ComponentModel;

namespace SoftwareMonkeys.WorkHub.Web.WebControls
{
	/// <summary>
	/// 
	/// </summary>
	public class DeleteLink : HyperLink
	{
		[Bindable(true)]
		[Browsable(true)]
		public string ConfirmMessage
		{
			get { return (string)ViewState["ConfirmMessage"]; }
			set { ViewState["ConfirmMessage"] = value; }
		}
		
		public DeleteLink()
		{
		}
		
		/*protected override void OnLoad(EventArgs e)
		{
			base.OnLoad(e);
			
			
		}*/
		
		public override void DataBind()
		{
			base.DataBind();
			
			if (Enabled)
			{
				string script = "return confirm('" + Escape(ConfirmMessage) + "');";
				
				Attributes.Add("onclick", script);
			}
		}
		
		private string Escape(string input)
		{
			return WebUtilities.EncodeJsString(input);
		}
	}
}
