/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\WebControls\EntityFormLabelItem.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Collections.Generic;
using System.Text;
using System.Web.UI.WebControls;
using System.ComponentModel;
using System.Web.UI;

namespace SoftwareMonkeys.WorkHub.Web.WebControls
{
    /// <summary>
    /// Represents an item in the entity form with a text label on it.
    /// </summary>
    public class EntityFormLabelItem : EntityFormSpecificItem
    {
        private Label label = new Label();
        public Label Label
        {
            get { return label; }
            set { label = value; }
        }

       /* [Bindable(true)]
        [Browsable(true)]
        public string Text
        {
            get { return label.Text; }
            set { label.Text = value; }
        }*/

        protected override void CreateFieldControls()
        {
            Label.ID = FieldControlID;
            FieldCell.Controls.Add(Label);
        }
    }
}
