/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\WebControls\EntityFormTextBoxItem.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Collections.Generic;
using System.Text;
using System.Web.UI.WebControls;
using System.ComponentModel;
using System.Web.UI;

namespace SoftwareMonkeys.WorkHub.Web.WebControls
{
    /// <summary>
    /// Displays a form item with a text box.
    /// </summary>
    public class EntityFormTextBoxItem : EntityFormSpecificItem
    {        	
        private TextBox textBox = new TextBox();
        public TextBox TextBox
        {
            get { return textBox; }
            set { textBox = value; }
        }

        protected override void CreateFieldControls()
        {
            TextBox.ID = FieldControlID;
            FieldCell.Controls.Add(TextBox);
        }
    }
}
