/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\WebControls\EntityFormSpecificItem.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel;
using System.Web.UI.WebControls;

namespace SoftwareMonkeys.WorkHub.Web.WebControls
{
    public abstract class EntityFormSpecificItem : EntityFormItem
    {
        /// <summary>
        /// Calls the CreateFieldControls function.
        /// </summary>
        /// <param name="e"></param>
        protected override void OnInit(EventArgs e)
        {
            base.OnInit(e);
            CreateFieldControls();
        }

        /// <summary>
        /// Overridden by derived classes to add the field controls to the item.
        /// </summary>
        protected virtual void CreateFieldControls()
        {

        }
    }
}
