/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Tests\BaseTestFixture.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Reflection;
using NUnit.Framework;
using SoftwareMonkeys.WorkHub.Diagnostics;
using SoftwareMonkeys.WorkHub.State;

namespace SoftwareMonkeys.WorkHub.Tests
{
	/// <summary>
	/// Provides a base implementation for all test fixtures.
	/// </summary>
	public abstract class BaseTestFixture
	{
		public string TestName = String.Empty;
		
		[SetUp]
		public virtual void Start()
		{
			TestName = TestContext.CurrentContext.Test.Name;
			
			TestUtilities.ClearTestingDirectory(this);
			
			// Create a new ID for the current test
			testID = Guid.NewGuid();
			
		}
		
		[TearDown]
		public virtual void End()
		{
			TestUtilities.ClearTestingDirectory(this);
		}
		
		private Guid testID;
		/// <summary>
		/// Gets a random ID specific to the current test.
		/// </summary>
		public Guid TestID
		{
			get {
				return testID;
			}
		}
	}
}
