/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Contracts\Web\ISiteMap.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;

namespace SoftwareMonkeys.WorkHub.Web
{
	/// <summary>
	/// Defines the interface of all site map components.
	/// </summary>
	public interface ISiteMap
	{
		void Add(ISiteMapNode item);
		
		void Remove(ISiteMapNode item);
	}
}
