/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Contracts\Web\ISiteMapManager.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;

namespace SoftwareMonkeys.WorkHub.Web
{
	/// <summary>
	/// Defines the interface of all site map manager components.
	/// </summary>
	public interface ISiteMapManager
	{
		/// <summary>
		/// Adds items to the provided site map.
		/// Note: The items are retrieved by the GetSiteMapItems() function.
		/// </summary>
		/// <param name="siteMap"></param>
		void Add(ISiteMap siteMap);
		
		/// <summary>
		/// Removes items from the provided site map.
		/// Note: The items are retrieved by the GetSiteMapItems() function.
		/// </summary>
		/// <param name="siteMap"></param>
		void Remove(ISiteMap siteMap);
		
		/// <summary>
		/// Retrieves the site map items that this manager is responsible for adding/removing.
		/// </summary>
		/// <returns></returns>
		ISiteMapNode[] GetSiteMapItems();
	}
}
