//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareMonkeys.WorkHub.Modules.Messages.Properties {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Language {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		public Language() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftwareMonkeys.WorkHub.Modules.Messages.Properties.Language", typeof(Language).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to All Messages.
		/// </summary>
		public static string AllMessages {
			get {
				return ResourceManager.GetString("AllMessages", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to (asc).
		/// </summary>
		public static string Asc {
			get {
				return ResourceManager.GetString("Asc", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Body.
		/// </summary>
		public static string Body {
			get {
				return ResourceManager.GetString("Body", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Comments.
		/// </summary>
		public static string Comments {
			get {
				return ResourceManager.GetString("Comments", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Are you sure you wish to delete this message?.
		/// </summary>
		public static string ConfirmDeleteMessage {
			get {
				return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Create.
		/// </summary>
		public static string Create {
			get {
				return ResourceManager.GetString("Create", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Create Message.
		/// </summary>
		public static string CreateMessage {
			get {
				return ResourceManager.GetString("CreateMessage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Enter the new message details in the form below..
		/// </summary>
		public static string CreateMessageIntro {
			get {
				return ResourceManager.GetString("CreateMessageIntro", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Delete.
		/// </summary>
		public static string Delete {
			get {
				return ResourceManager.GetString("Delete", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Delete this .
		/// </summary>
		public static string DeleteMessageToolTip {
			get {
				return ResourceManager.GetString("DeleteMessageToolTip", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to (desc).
		/// </summary>
		public static string Desc {
			get {
				return ResourceManager.GetString("Desc", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Discussions.
		/// </summary>
		public static string Discussions {
			get {
				return ResourceManager.GetString("Discussions", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The latest discussion posts are shown below..
		/// </summary>
		public static string DiscussionsIntro {
			get {
				return ResourceManager.GetString("DiscussionsIntro", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Edit.
		/// </summary>
		public static string Edit {
			get {
				return ResourceManager.GetString("Edit", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Edit Message.
		/// </summary>
		public static string EditMessage {
			get {
				return ResourceManager.GetString("EditMessage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Edit the message details in the form below..
		/// </summary>
		public static string EditMessageIntro {
			get {
				return ResourceManager.GetString("EditMessageIntro", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Edit this message.
		/// </summary>
		public static string EditMessageToolTip {
			get {
				return ResourceManager.GetString("EditMessageToolTip", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ID.
		/// </summary>
		public static string ID {
			get {
				return ResourceManager.GetString("ID", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Inbox.
		/// </summary>
		public static string Inbox {
			get {
				return ResourceManager.GetString("Inbox", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Index.
		/// </summary>
		public static string Index {
			get {
				return ResourceManager.GetString("Index", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Is Public.
		/// </summary>
		public static string IsPublic {
			get {
				return ResourceManager.GetString("IsPublic", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Yes this message is visible to the public..
		/// </summary>
		public static string IsPublicNote {
			get {
				return ResourceManager.GetString("IsPublicNote", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Message.
		/// </summary>
		public static string Message {
			get {
				return ResourceManager.GetString("Message", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The selected message was deleted successfully..
		/// </summary>
		public static string MessageDeleted {
			get {
				return ResourceManager.GetString("MessageDeleted", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Message Details.
		/// </summary>
		public static string MessageDetails {
			get {
				return ResourceManager.GetString("MessageDetails", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Please select at least one project that this message is assigned to..
		/// </summary>
		public static string MessageProjectRequired {
			get {
				return ResourceManager.GetString("MessageProjectRequired", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Please select at least one recipient..
		/// </summary>
		public static string MessageRecipientsRequired {
			get {
				return ResourceManager.GetString("MessageRecipientsRequired", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Messages.
		/// </summary>
		public static string Messages {
			get {
				return ResourceManager.GetString("Messages", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The message was sent successfully..
		/// </summary>
		public static string MessageSaved {
			get {
				return ResourceManager.GetString("MessageSaved", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Messages: Inbox.
		/// </summary>
		public static string MessagesInbox {
			get {
				return ResourceManager.GetString("MessagesInbox", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The following messages have been sent to you..
		/// </summary>
		public static string MessagesInboxIntro {
			get {
				return ResourceManager.GetString("MessagesInboxIntro", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Messages XML.
		/// </summary>
		public static string MessagesXml {
			get {
				return ResourceManager.GetString("MessagesXml", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The links below display messages in XML format..
		/// </summary>
		public static string MessagesXmlIntro {
			get {
				return ResourceManager.GetString("MessagesXmlIntro", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Messages XML Pages.
		/// </summary>
		public static string MessagesXmlPages {
			get {
				return ResourceManager.GetString("MessagesXmlPages", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Please enter a title for this message..
		/// </summary>
		public static string MessageTitleRequired {
			get {
				return ResourceManager.GetString("MessageTitleRequired", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The message was updated successfully..
		/// </summary>
		public static string MessageUpdated {
			get {
				return ResourceManager.GetString("MessageUpdated", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to N/A.
		/// </summary>
		public static string NA {
			get {
				return ResourceManager.GetString("NA", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to New Message Details.
		/// </summary>
		public static string NewMessageDetails {
			get {
				return ResourceManager.GetString("NewMessageDetails", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No body was provided for this message..
		/// </summary>
		public static string NoBodyForMessage {
			get {
				return ResourceManager.GetString("NoBodyForMessage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No discussions have been started..
		/// </summary>
		public static string NoDiscussions {
			get {
				return ResourceManager.GetString("NoDiscussions", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No messages have been created..
		/// </summary>
		public static string NoMessages {
			get {
				return ResourceManager.GetString("NoMessages", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to This message has no parent..
		/// </summary>
		public static string NoParentForMessage {
			get {
				return ResourceManager.GetString("NoParentForMessage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No-one has replied to this message..
		/// </summary>
		public static string NoRepliesForMessage {
			get {
				return ResourceManager.GetString("NoRepliesForMessage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to You have received the following message at:
		///${Application.Title}
		///${Application.Url}
		///
		///${Message.Title}
		///${Message.Body}
		///
		///From:
		///${Message.Sender.Name}
		///
		///The message can be viewed here:
		///${Message.Url}.
		/// </summary>
		public static string NotifyMessageBody {
			get {
				return ResourceManager.GetString("NotifyMessageBody", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Organization.
		/// </summary>
		public static string Organization {
			get {
				return ResourceManager.GetString("Organization", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Parent Message.
		/// </summary>
		public static string ParentMessage {
			get {
				return ResourceManager.GetString("ParentMessage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Parent Messages.
		/// </summary>
		public static string ParentMessages {
			get {
				return ResourceManager.GetString("ParentMessages", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Post.
		/// </summary>
		public static string Post {
			get {
				return ResourceManager.GetString("Post", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Post Message.
		/// </summary>
		public static string PostMessage {
			get {
				return ResourceManager.GetString("PostMessage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Previous.
		/// </summary>
		public static string Previous {
			get {
				return ResourceManager.GetString("Previous", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Project.
		/// </summary>
		public static string Project {
			get {
				return ResourceManager.GetString("Project", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Projects.
		/// </summary>
		public static string Projects {
			get {
				return ResourceManager.GetString("Projects", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Re.
		/// </summary>
		public static string Re {
			get {
				return ResourceManager.GetString("Re", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Read.
		/// </summary>
		public static string Read {
			get {
				return ResourceManager.GetString("Read", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Recent Discussions.
		/// </summary>
		public static string RecentDiscussions {
			get {
				return ResourceManager.GetString("RecentDiscussions", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Recipients.
		/// </summary>
		public static string Recipients {
			get {
				return ResourceManager.GetString("Recipients", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Replies.
		/// </summary>
		public static string Replies {
			get {
				return ResourceManager.GetString("Replies", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Reply.
		/// </summary>
		public static string Reply {
			get {
				return ResourceManager.GetString("Reply", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Reply to this message.
		/// </summary>
		public static string ReplyToMessageToolTip {
			get {
				return ResourceManager.GetString("ReplyToMessageToolTip", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Save.
		/// </summary>
		public static string Save {
			get {
				return ResourceManager.GetString("Save", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Select Message.
		/// </summary>
		public static string SelectMessage {
			get {
				return ResourceManager.GetString("SelectMessage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Select Project.
		/// </summary>
		public static string SelectProject {
			get {
				return ResourceManager.GetString("SelectProject", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Select Recipients.
		/// </summary>
		public static string SelectRecipients {
			get {
				return ResourceManager.GetString("SelectRecipients", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Send.
		/// </summary>
		public static string Send {
			get {
				return ResourceManager.GetString("Send", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Sender.
		/// </summary>
		public static string Sender {
			get {
				return ResourceManager.GetString("Sender", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Sent.
		/// </summary>
		public static string Sent {
			get {
				return ResourceManager.GetString("Sent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Sent Messages.
		/// </summary>
		public static string SentMessages {
			get {
				return ResourceManager.GetString("SentMessages", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The messages you have sent/posted are shown below..
		/// </summary>
		public static string SentMessagesIntro {
			get {
				return ResourceManager.GetString("SentMessagesIntro", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Start Discussion.
		/// </summary>
		public static string StartDiscussion {
			get {
				return ResourceManager.GetString("StartDiscussion", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Subject.
		/// </summary>
		public static string Subject {
			get {
				return ResourceManager.GetString("Subject", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Sub Messages.
		/// </summary>
		public static string SubMessages {
			get {
				return ResourceManager.GetString("SubMessages", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Title.
		/// </summary>
		public static string Title {
			get {
				return ResourceManager.GetString("Title", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Unread.
		/// </summary>
		public static string Unread {
			get {
				return ResourceManager.GetString("Unread", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Update.
		/// </summary>
		public static string Update {
			get {
				return ResourceManager.GetString("Update", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to View.
		/// </summary>
		public static string View {
			get {
				return ResourceManager.GetString("View", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Vote.
		/// </summary>
		public static string Vote {
			get {
				return ResourceManager.GetString("Vote", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to XML.
		/// </summary>
		public static string Xml {
			get {
				return ResourceManager.GetString("Xml", resourceCulture);
			}
		}
	}
}
