//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareMonkeys.WorkHub.Modules.Components.Properties {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Language {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Language() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftwareMonkeys.WorkHub.Modules.Components.Properties.Language", typeof(Language).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to All Components.
		/// </summary>
		public static string AllComponents {
			get {
				return ResourceManager.GetString("AllComponents", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to (asc).
		/// </summary>
		public static string Asc {
			get {
				return ResourceManager.GetString("Asc", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Component.
		/// </summary>
		public static string Component {
			get {
				return ResourceManager.GetString("Component", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The selected component was deleted successfully..
		/// </summary>
		public static string ComponentDeleted {
			get {
				return ResourceManager.GetString("ComponentDeleted", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Component Details.
		/// </summary>
		public static string ComponentDetails {
			get {
				return ResourceManager.GetString("ComponentDetails", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Please enter a name for this component..
		/// </summary>
		public static string ComponentNameRequired {
			get {
				return ResourceManager.GetString("ComponentNameRequired", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Please select at least one project that this component is assigned to..
		/// </summary>
		public static string ComponentProjectRequired {
			get {
				return ResourceManager.GetString("ComponentProjectRequired", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Components.
		/// </summary>
		public static string Components {
			get {
				return ResourceManager.GetString("Components", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The component was saved successfully..
		/// </summary>
		public static string ComponentSaved {
			get {
				return ResourceManager.GetString("ComponentSaved", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Create and manage components in the index below..
		/// </summary>
		public static string ComponentsIntro {
			get {
				return ResourceManager.GetString("ComponentsIntro", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Component Summary.
		/// </summary>
		public static string ComponentSummary {
			get {
				return ResourceManager.GetString("ComponentSummary", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Components XML.
		/// </summary>
		public static string ComponentsXml {
			get {
				return ResourceManager.GetString("ComponentsXml", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The components below display components in XML format..
		/// </summary>
		public static string ComponentsXmlIntro {
			get {
				return ResourceManager.GetString("ComponentsXmlIntro", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Components XML Pages.
		/// </summary>
		public static string ComponentsXmlPages {
			get {
				return ResourceManager.GetString("ComponentsXmlPages", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The title of the component is in use, please try a different one..
		/// </summary>
		public static string ComponentTitleTaken {
			get {
				return ResourceManager.GetString("ComponentTitleTaken", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Component Type.
		/// </summary>
		public static string ComponentType {
			get {
				return ResourceManager.GetString("ComponentType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Component Type Details.
		/// </summary>
		public static string ComponentTypeDetails {
			get {
				return ResourceManager.GetString("ComponentTypeDetails", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Please enter a name for the component type..
		/// </summary>
		public static string ComponentTypeNameRequired {
			get {
				return ResourceManager.GetString("ComponentTypeNameRequired", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Please select at least one project for the component type..
		/// </summary>
		public static string ComponentTypeProjectRequired {
			get {
				return ResourceManager.GetString("ComponentTypeProjectRequired", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Component Types.
		/// </summary>
		public static string ComponentTypes {
			get {
				return ResourceManager.GetString("ComponentTypes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Create and manage component types using the index below..
		/// </summary>
		public static string ComponentTypesIntro {
			get {
				return ResourceManager.GetString("ComponentTypesIntro", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The component was updated successfully..
		/// </summary>
		public static string ComponentUpdated {
			get {
				return ResourceManager.GetString("ComponentUpdated", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Please enter a URL for the component..
		/// </summary>
		public static string ComponentUrlRequired {
			get {
				return ResourceManager.GetString("ComponentUrlRequired", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Are you sure you want to cancel creating this component?.
		/// </summary>
		public static string ConfirmCancelCreateComponent {
			get {
				return ResourceManager.GetString("ConfirmCancelCreateComponent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Are you sure you wish to delete this component and all related data?.
		/// </summary>
		public static string ConfirmDeleteComponent {
			get {
				return ResourceManager.GetString("ConfirmDeleteComponent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Are you sure you want to delete the component type?.
		/// </summary>
		public static string ConfirmDeleteComponentType {
			get {
				return ResourceManager.GetString("ConfirmDeleteComponentType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Create Component.
		/// </summary>
		public static string CreateComponent {
			get {
				return ResourceManager.GetString("CreateComponent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Enter the details of the new component in the form below..
		/// </summary>
		public static string CreateComponentIntro {
			get {
				return ResourceManager.GetString("CreateComponentIntro", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Create Component Type.
		/// </summary>
		public static string CreateComponentType {
			get {
				return ResourceManager.GetString("CreateComponentType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Enter the details of the new component type into the form below..
		/// </summary>
		public static string CreateComponentTypeIntro {
			get {
				return ResourceManager.GetString("CreateComponentTypeIntro", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Delete.
		/// </summary>
		public static string Delete {
			get {
				return ResourceManager.GetString("Delete", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Delete this component.
		/// </summary>
		public static string DeleteComponentToolTip {
			get {
				return ResourceManager.GetString("DeleteComponentToolTip", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Delete this component type.
		/// </summary>
		public static string DeleteComponentTypeToolTip {
			get {
				return ResourceManager.GetString("DeleteComponentTypeToolTip", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to (desc).
		/// </summary>
		public static string Desc {
			get {
				return ResourceManager.GetString("Desc", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Description.
		/// </summary>
		public static string Description {
			get {
				return ResourceManager.GetString("Description", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Edit.
		/// </summary>
		public static string Edit {
			get {
				return ResourceManager.GetString("Edit", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Edit Component.
		/// </summary>
		public static string EditComponent {
			get {
				return ResourceManager.GetString("EditComponent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Edit the component details in the form below..
		/// </summary>
		public static string EditComponentIntro {
			get {
				return ResourceManager.GetString("EditComponentIntro", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Edit this component.
		/// </summary>
		public static string EditComponentToolTip {
			get {
				return ResourceManager.GetString("EditComponentToolTip", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Edit Component Type.
		/// </summary>
		public static string EditComponentType {
			get {
				return ResourceManager.GetString("EditComponentType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Edit the details of the component type in the form below..
		/// </summary>
		public static string EditComponentTypeIntro {
			get {
				return ResourceManager.GetString("EditComponentTypeIntro", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Edit this component type.
		/// </summary>
		public static string EditComponentTypeToolTip {
			get {
				return ResourceManager.GetString("EditComponentTypeToolTip", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Guide.
		/// </summary>
		public static string Guide {
			get {
				return ResourceManager.GetString("Guide", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ID.
		/// </summary>
		public static string ID {
			get {
				return ResourceManager.GetString("ID", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Is Public.
		/// </summary>
		public static string IsPublic {
			get {
				return ResourceManager.GetString("IsPublic", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to N/A.
		/// </summary>
		public static string NA {
			get {
				return ResourceManager.GetString("NA", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Name.
		/// </summary>
		public static string Name {
			get {
				return ResourceManager.GetString("Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to New Component Details.
		/// </summary>
		public static string NewComponentDetails {
			get {
				return ResourceManager.GetString("NewComponentDetails", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to New Component Type Details.
		/// </summary>
		public static string NewComponentTypeDetails {
			get {
				return ResourceManager.GetString("NewComponentTypeDetails", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No components found..
		/// </summary>
		public static string NoComponents {
			get {
				return ResourceManager.GetString("NoComponents", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No components have been associated with this type..
		/// </summary>
		public static string NoComponentsForComponentType {
			get {
				return ResourceManager.GetString("NoComponentsForComponentType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No component type has been specified..
		/// </summary>
		public static string NoComponentTypeForComponent {
			get {
				return ResourceManager.GetString("NoComponentTypeForComponent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No component types found..
		/// </summary>
		public static string NoComponentTypes {
			get {
				return ResourceManager.GetString("NoComponentTypes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No description has been provided..
		/// </summary>
		public static string NoDescription {
			get {
				return ResourceManager.GetString("NoDescription", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No parent components assigned to this component..
		/// </summary>
		public static string NoParentComponentsForComponent {
			get {
				return ResourceManager.GetString("NoParentComponentsForComponent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No related components assigned to this component..
		/// </summary>
		public static string NoRelatedComponentsForComponent {
			get {
				return ResourceManager.GetString("NoRelatedComponentsForComponent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No sub components assigned to this component..
		/// </summary>
		public static string NoSubComponentsForComponent {
			get {
				return ResourceManager.GetString("NoSubComponentsForComponent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No summary has been provided for this component..
		/// </summary>
		public static string NoSummary {
			get {
				return ResourceManager.GetString("NoSummary", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Organization.
		/// </summary>
		public static string Organization {
			get {
				return ResourceManager.GetString("Organization", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Parent Components.
		/// </summary>
		public static string ParentComponents {
			get {
				return ResourceManager.GetString("ParentComponents", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Planning.
		/// </summary>
		public static string Planning {
			get {
				return ResourceManager.GetString("Planning", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Project.
		/// </summary>
		public static string Project {
			get {
				return ResourceManager.GetString("Project", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Projects.
		/// </summary>
		public static string Projects {
			get {
				return ResourceManager.GetString("Projects", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Related Components.
		/// </summary>
		public static string RelatedComponents {
			get {
				return ResourceManager.GetString("RelatedComponents", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Save.
		/// </summary>
		public static string Save {
			get {
				return ResourceManager.GetString("Save", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Select Component.
		/// </summary>
		public static string SelectComponent {
			get {
				return ResourceManager.GetString("SelectComponent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Select Type.
		/// </summary>
		public static string SelectComponentType {
			get {
				return ResourceManager.GetString("SelectComponentType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Select Project.
		/// </summary>
		public static string SelectProject {
			get {
				return ResourceManager.GetString("SelectProject", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Sub Components.
		/// </summary>
		public static string SubComponents {
			get {
				return ResourceManager.GetString("SubComponents", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Summary.
		/// </summary>
		public static string Summary {
			get {
				return ResourceManager.GetString("Summary", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Technical.
		/// </summary>
		public static string Technical {
			get {
				return ResourceManager.GetString("Technical", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Title.
		/// </summary>
		public static string Title {
			get {
				return ResourceManager.GetString("Title", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Update.
		/// </summary>
		public static string Update {
			get {
				return ResourceManager.GetString("Update", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to View.
		/// </summary>
		public static string View {
			get {
				return ResourceManager.GetString("View", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to XML.
		/// </summary>
		public static string Xml {
			get {
				return ResourceManager.GetString("Xml", resourceCulture);
			}
		}
	}
}
