/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\Validation\UserValidation.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Business;

namespace SoftwareMonkeys.WorkHub.Web.Validation
{
	/// <summary>
	/// Provides the validation messages related to users.
	/// </summary>
	public class UserValidation : ValidationFacade
	{
		public UserValidation()
		{
			AddError("Username", "Unique", DynamicLanguage.GetText(GetType(), "UsernameTaken"));
			AddError("Username", "Required", DynamicLanguage.GetText(GetType(), "UsernameRequired"));
			AddError("FirstName", "Required", DynamicLanguage.GetText(GetType(), "FirstNameRequired"));
			AddError("LastName", "Required", DynamicLanguage.GetText(GetType(), "LastNameRequired"));
			AddError("Email", "Required", DynamicLanguage.GetText(GetType(), "EmailRequired"));
			AddError("Email", "Unique", DynamicLanguage.GetText(GetType(), "EmailTaken"));
			AddError("Email", "Email", DynamicLanguage.GetText(GetType(), "InvalidEmail"));
			AddError("Password", "Required", DynamicLanguage.GetText(GetType(), "PasswordRequired"));
		}
	}
}
