/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\Validation\ValidationMessageNotFoundException.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Entities;

namespace SoftwareMonkeys.WorkHub.Web
{
	/// <summary>
	/// Thrown when a validation error message can't be found.
	/// </summary>
	public class ValidationMessageNotFoundException : Exception
	{
		public ValidationMessageNotFoundException(IEntity entity, string propertyName, string validatorName) : base("Can't find error message for failure of '" + validatorName + "' validator on '" + propertyName + "' property of '" + entity.ShortTypeName + "' entity type." + Environment.NewLine + "Add it via ValidationFacade.AddError(\"" + propertyName + "\", \"" + validatorName + "\", \"[errorLanguageKey]\") function.")
		{
		}
	}
}
