/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Configuration.Tests\MockConfigSaver.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;

namespace SoftwareMonkeys.WorkHub.Configuration.Tests
{
	/// <summary>
	/// Provides a mock/test implementation for the config saver component.
	/// </summary>
	public class MockConfigSaver : ConfigSaver
	{
	
	}
}
