/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Entities.Tests\Entities\MockRequiredEntity.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Tests.Entities;

namespace SoftwareMonkeys.WorkHub.Entities.Tests.Entities
{
	/// <summary>
	/// 
	/// </summary>
	[Entity]
	public class MockRequiredEntity : BaseTestEntity
	{
		private string testProperty = String.Empty;
		[Required]
		public string TestProperty
		{
			get { return testProperty; }
			set { testProperty = value; }
		}
		
		public MockRequiredEntity()
		{
		}
	}
}
