/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Entities.Tests\Entities\MockSyncEntity.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;

namespace SoftwareMonkeys.WorkHub.Entities.Tests.Entities
{
	/// <summary>
	/// Represents an entity with a synchronous (two way) reference between it and the MockEntity.
	/// </summary>
	[Entity]
	public class MockSyncEntity : BaseEntity
	{
		private MockEntity[] entities;
		[Reference(
			MirrorPropertyName="SyncEntities",
		    CountPropertyName="TotalEntities")
		]
		public MockEntity[] Entities
		{
			get { return entities; }
			set { entities = value; }
		}
		
		private int totalEntities = 0;
		public int TotalEntities
		{
			get { return totalEntities; }
			set { totalEntities = value; }
		}
		
		public MockSyncEntity()
		{
		}
	}
}
