/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Entities.Tests\Entities\MockPublicEntity.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;

namespace SoftwareMonkeys.WorkHub.Entities.Tests.Entities
{
	/// <summary>
	/// 
	/// </summary>
	[Entity("MockPublicEntity")]
	public class MockPublicEntity : BaseEntity
	{
		public MockPublicEntity()
		{
		}
	}
}
