/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Contracts/Entities\IPagingLocation.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;

namespace SoftwareMonkeys.WorkHub.Entities
{
	/// <summary>
	/// 
	/// </summary>
	public interface IPagingLocation
	{
		int PageSize {get;set;}
		int PageIndex {get;set;}
		int AbsoluteTotal {get;set;}
	}
}
