/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Contracts\Entities\IUniqueEntity.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;

namespace SoftwareMonkeys.WorkHub.Entities
{
	/// <summary>
	/// Defines the interface of all entities that are required to be unique according to a specific property such as UniqueKey.
	/// </summary>
	public interface IUniqueEntity : IEntity
	{
		string UniqueKey {get;}
	}
}
