/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Contracts\Entities\IUserRole.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Data;
using System.Configuration;

namespace SoftwareMonkeys.WorkHub.Entities
{
    /// <summary>
    /// Defines the interface for a user role in the application.
    /// </summary>
    public interface IUserRole : ISimple
    {
        string Name { get;set; }
		//IUserPermission[] Permissions { get;set; }
		IUser[] Users {get;set;}
		//Guid[] UserIDs {get;set;}
		//void AddUser(IUser user);
		//void RemoveUser(IUser user);
    }
}