<%--
====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\WWW\Admin\Tests\ChangePassword.aspx

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================

--%>

<%@ Page Language="C#" autoeventwireup="true" %>
<%@ Import namespace="SoftwareMonkeys.WorkHub.Entities" %>
<%@ Import namespace="SoftwareMonkeys.WorkHub.Business" %>
<%@ Import namespace="SoftwareMonkeys.WorkHub.Diagnostics" %>
<script runat="server">

private void Page_Init(object sender, EventArgs e)
{
	string url = String.Empty;
	using (LogGroup logGroup = LogGroup.StartDebug("Initializing the test change password page."))
	{
		string email = Request.QueryString["Email"];
		
		if (email == null || email == String.Empty)
			throw new Exception("No email specified by the 'Email' query string.");
	
		User user = RetrieveStrategy.New<User>(false).Retrieve<User>("Email", email);
		
		url = Request.ApplicationPath + "/ChangePassword.aspx?u=" + Request.QueryString["Email"] + "&p=" + user.Password;
	}
	
	Response.Redirect(url);
}

</script>