<%--
====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\WWW\Admin\Tests\\PrepareTestAutoUpdate.aspx

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================

--%>

<%@ Page Language="C#" Title="Prepare Test Import" autoeventwireup="true" %>
<%@ Import Namespace="SoftwareMonkeys.WorkHub.Entities" %>
<%@ Import Namespace="SoftwareMonkeys.WorkHub.Business" %>
<%@ Import Namespace="SoftwareMonkeys.WorkHub.Business.Security" %>
<%@ Import Namespace="SoftwareMonkeys.WorkHub.Configuration" %>
<%@ Import Namespace="System.Reflection" %>
<%@ Import Namespace="SoftwareMonkeys.WorkHub.Web" %>
<%@ Import Namespace="SoftwareMonkeys.WorkHub.Web.WebControls" %>
<%@ Import Namespace="SoftwareMonkeys.WorkHub.Web.Data" %>
<%@ Import Namespace="SoftwareMonkeys.WorkHub.Web.Security" %>
<%@ Import namespace="System.IO" %>
<%@ Import namespace="System.Xml" %>
<%@ Import namespace="System.Xml.Serialization" %>
<%@ Import namespace="SoftwareMonkeys.WorkHub.Data" %>
<%@ Import namespace="SoftwareMonkeys.WorkHub.State" %>
<%@ Import namespace="SoftwareMonkeys.WorkHub.Diagnostics" %>
<script runat="server">


protected override void OnLoad(EventArgs e)
{
	using (LogGroup logGroup = LogGroup.StartDebug("Preparing to test the auto update feature."))
	{
			SetAllowConfig();
	}
	base.OnLoad(e);
}

private void SetAllowConfig()
{
	string filePath = Server.MapPath(Request.ApplicationPath + "/AllowAutoUpdate.config");
	using (StreamWriter writer = File.CreateText(filePath))
	{
		writer.Write(true.ToString());
	}
	
}

</script>
<html>
<head runat="server">
</head>
<body>
<form runat="server">
Done...<br/>
</form>
</body>
</html>