/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business\AssemblyContainsStrategiesAttribute.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;

namespace SoftwareMonkeys.WorkHub.Business
{
	/// <summary>
	/// 
	/// </summary>
	[AttributeUsage(AttributeTargets.Assembly)]
	public class AssemblyContainsStrategiesAttribute : Attribute
	{
		private bool areTestStrategies = false;
		/// <summary>
		/// Gets/sets a flag indicating whether the strategies in this assembly are test/mock strategies.
		/// </summary>
		public bool AreTestStrategies
		{
			get  { return areTestStrategies; }
			set  { areTestStrategies = value; }
		}
		
		public AssemblyContainsStrategiesAttribute()
		{
		}
		
		public AssemblyContainsStrategiesAttribute(bool areTestStrategies)
		{
			AreTestStrategies = areTestStrategies;
		}
	}
}
