/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business\BaseSaveReaction.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Entities;
using SoftwareMonkeys.WorkHub.Data;
using SoftwareMonkeys.WorkHub.Business;
using SoftwareMonkeys.WorkHub.Business.Security;
using SoftwareMonkeys.WorkHub.Diagnostics;

namespace SoftwareMonkeys.WorkHub.Business
{
	/// <summary>
	/// Reacts to a save action.
	/// </summary>
	[Reaction("Save", "IEntity")]
	public abstract class BaseSaveReaction : BaseReaction, ISaveReaction
	{
		
		public BaseSaveReaction()
		{
		}
		
		#region New functions	
		/// <summary>
		/// Creates new reactions to a save of the specified type.
		/// </summary>
		static public ISaveReaction[] New<T>()
		{
			return ReactionState.Reactions.Creator.NewSaveReactions(typeof(T).Name);
		}
		
		/// <summary>
		/// Creates new reactions to a save of the provided type.
		/// </summary>
		/// <param name="entity"></param>
		/// <returns>A save reaction for the provided type.</returns>
		static public ISaveReaction[] New(IEntity entity)
		{
			if (entity == null)
				throw new ArgumentNullException("entity");
			
			return ReactionState.Reactions.Creator.NewSaveReactions(entity.ShortTypeName);
		}
		
		/// <summary>
		/// Creates new reactions to a save of the specified type.
		/// </summary>
		/// <param name="typeName">The short name of the type involved in the reaction.</param>
		static public ISaveReaction[] New(string typeName)
		{
			return ReactionState.Reactions.Creator.NewSaveReactions(typeName);
		}
		
		#endregion
	}
}
