/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business\BaseValidatePropertyStrategy.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Collections.Generic;
using System.Reflection;
using SoftwareMonkeys.WorkHub.Entities;

namespace SoftwareMonkeys.WorkHub.Business
{
	/// <summary>
	/// 
	/// </summary>
	public abstract class BaseValidatePropertyStrategy : BaseStrategy, IValidatePropertyStrategy
	{		
		public BaseValidatePropertyStrategy()
		{
		}
		
		public void Validate(IEntity entity, PropertyInfo property, IValidatePropertyAttribute attribute)
		{
			if (!IsValid(entity, property, attribute))
			{
				entity.Validator.AddFailure(property.Name, attribute);
			}
		}
		
		public abstract bool IsValid(IEntity entity, PropertyInfo property, IValidatePropertyAttribute attribute);
		
		public object GetValue(IEntity entity, PropertyInfo property)
		{
			return property.GetValue(entity, null);
		}
		
		public string GetStringValue(IEntity entity, PropertyInfo property)
		{
			return (string)GetValue(entity, property);
		}
	}
}
