/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business\BaseUpdateReaction.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Entities;
using SoftwareMonkeys.WorkHub.Data;
using SoftwareMonkeys.WorkHub.Business.Security;
using SoftwareMonkeys.WorkHub.Diagnostics;

namespace SoftwareMonkeys.WorkHub.Business
{
	/// <summary>
	/// Used to update entities.
	/// </summary>
	[Reaction("Update", "IEntity")]
	public abstract class BaseUpdateReaction : BaseReaction, IUpdateReaction
	{		
		public BaseUpdateReaction()
		{
		}
		
		public BaseUpdateReaction(string typeName) : base(typeName)
		{}
	
		#region New functions
		/// <summary>
		/// Creates new reactions to an update of the provided entity.
		/// </summary>
		/// <param name="entity">The entity involved in the reaction.</param>
		static public IUpdateReaction[] New(IEntity entity)
		{
			return New(entity.ShortTypeName);
		}
		
		/// <summary>
		/// Creates new reactions to an update of the specified type.
		/// </summary>
		static public IUpdateReaction[] New<T>()
		{
			return New(typeof(T).Name);
		}
		
		/// <summary>
		/// Creates new reactions to an update of the specified type.
		/// </summary>
		/// <param name="typeName">The short name of the type involved in the reaction.</param>
		static public IUpdateReaction[] New(string typeName)
		{
			IUpdateReaction[] reactions = null;
			using (LogGroup logGroup = LogGroup.Start("Creating new update reactions.", NLog.LogLevel.Debug))
			{
				LogWriter.Debug("Type name: " + typeName);
				reactions = ReactionState.Reactions.Creator.NewUpdateReactions(typeName);
			}
			return reactions;
		}
		
		#endregion
	}
}
