/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business\DeleteSubEntityStrategy.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Entities;

namespace SoftwareMonkeys.WorkHub.Business
{
	/// <summary>
	/// 
	/// </summary>
	[Strategy("Delete", "ISubEntity")]
	public class DeleteSubEntityStrategy : DeleteStrategy
	{
		public override void Delete(IEntity entity)
		{
			if (entity is ISubEntity)
			{				
				ISubEntity subEntity = (ISubEntity)entity;
				
				if (subEntity.Parent == null)
					ActivateStrategy.New(subEntity, RequireAuthorisation).Activate(subEntity, subEntity.ParentPropertyName);
				
				IEntity parent = subEntity.Parent;
				
				if (parent == null)
					throw new Exception("No parent assigned to sub entity.");
				
				base.Delete(subEntity);
				
				RefreshNumbers(subEntity.Parent, subEntity.ItemsPropertyName);
			}
			else
			{
				throw new ArgumentException("entity must be ISubEntity");
			}
			
		}
		
		public virtual void RefreshNumbers(IEntity parentEntity, string itemsPropertyName)
		{
			RefreshSubEntityNumbersStrategy.New(RequireAuthorisation).Refresh(parentEntity, itemsPropertyName);
		}
	}
}
