/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business\InvalidEntityException.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Entities;

namespace SoftwareMonkeys.WorkHub.Business
{
	/// <summary>
	/// Thrown when attempting an operation which requires entity.IsValid to be true but is currently false.
	/// </summary>
	public class InvalidEntityException : Exception
	{
		private IEntity entity;
		public IEntity Entity
		{
			get { return entity; }
			set { entity = value; }
		}
		
		public InvalidEntityException(IEntity entity) : base("The '" + entity.ShortTypeName + "' entity has not been validated.")
		{
			Entity = entity;
		}
	}
}
