/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business\ReactionFileNamer.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.IO;

using SoftwareMonkeys.WorkHub.Data;
using SoftwareMonkeys.WorkHub.State;

namespace SoftwareMonkeys.WorkHub.Business
{
	/// <summary>
	/// Used to create file names/paths for reaction components.
	/// </summary>
	public class ReactionFileNamer
	{
		private string reactionsInfoFilePath;
		/// <summary>
		/// Gets the path to the file containing the reaction info.
		/// </summary>
		public virtual string ReactionsInfoFilePath
		{
			get {
				if (reactionsInfoFilePath == null || reactionsInfoFilePath == String.Empty)
				{
					if (StateAccess.IsInitialized)
						reactionsInfoFilePath = StateAccess.State.PhysicalApplicationPath
							+ Path.DirectorySeparatorChar + "App_Data"
							+ Path.DirectorySeparatorChar + "Reactions.xml";
				}
				return reactionsInfoFilePath;
			}
			set { reactionsInfoFilePath = value; }
		}
		
		public ReactionFileNamer()
		{
		}
	}
}
