/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business\ReactionNotFoundException.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;

namespace SoftwareMonkeys.WorkHub.Business
{
	/// <summary>
	/// Indicates that a reaction for the provided type and action could not be found.
	/// </summary>
	public class ReactionNotFoundException : ApplicationException
	{
		private string action;
		/// <summary>
		/// Gets/sets the action being performed by the reaction.
		/// </summary>
		public string Action
		{
			get { return action; }
			set { action = value; }
		}
		
		private string typeName;
		/// <summary>
		/// Gets/sets the name of the type involved in the reaction.
		/// </summary>
		public string TypeName
		{
			get { return typeName; }
			set { typeName = value; }
		}
		
		public ReactionNotFoundException(string action, string typeName) : base("A reaction could not be found to carry out the '" + action + "' action with the '" + typeName + "' entity type.")
		{
			Action = action;
			TypeName = typeName;
		}
	}
}
