/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business\StrategySaver.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.IO;
using SoftwareMonkeys.WorkHub.Data;
using System.Xml.Serialization;
using SoftwareMonkeys.WorkHub.Diagnostics;

namespace SoftwareMonkeys.WorkHub.Business
{
	/// <summary>
	/// Used to save strategy components to file.
	/// </summary>
	public class StrategySaver
	{
		private StrategyFileNamer fileNamer;
		/// <summary>
		/// Gets/sets the file namer used to create file names/paths.
		/// </summary>
		public StrategyFileNamer FileNamer
		{
			get {
				if (fileNamer == null)
					fileNamer = new StrategyFileNamer();
				return fileNamer; }
			set { fileNamer = value; }
		}
		
		public StrategySaver()
		{
		}
		
		/// <summary>
		/// Saves the provided strategies to file.
		/// </summary>
		/// <param name="strategies">An array of the strategies to save to file.</param>
		public void SaveToFile(StrategyInfo[] strategies)
		{
			// Logging disabled to boost performance
			//using (LogGroup logGroup = LogGroup.StartDebug("Saving the provided strategies to XML file."))
			//{
			string path = FileNamer.StrategiesInfoFilePath;
			
			//LogWriter.Debug("Path : " + path);
			
			if (!Directory.Exists(Path.GetDirectoryName(path)))
				Directory.CreateDirectory(Path.GetDirectoryName(path));
			
			using (StreamWriter writer = File.CreateText(path))
			{
				XmlSerializer serializer = new XmlSerializer(strategies.GetType());
				serializer.Serialize(writer, strategies);
				writer.Close();
			}
			//}
		}
	}
}
