/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business\StrategyFileNamer.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.IO;
using SoftwareMonkeys.WorkHub.Business.Security;
using SoftwareMonkeys.WorkHub.Data;
using SoftwareMonkeys.WorkHub.State;

namespace SoftwareMonkeys.WorkHub.Business
{
	/// <summary>
	/// Used to create file names/paths for strategy components.
	/// </summary>
	public class StrategyFileNamer
	{
		private string strategiesInfoFilePath;
		/// <summary>
		/// Gets the path to the file containing the strategy info.
		/// </summary>
		public virtual string StrategiesInfoFilePath
		{
			get {
				if (strategiesInfoFilePath == null || strategiesInfoFilePath == String.Empty)
				{
					if (StateAccess.IsInitialized)
						strategiesInfoFilePath = StateAccess.State.PhysicalApplicationPath
							+ Path.DirectorySeparatorChar + "App_Data"
							+ Path.DirectorySeparatorChar + "Strategies.xml";
				}
				return strategiesInfoFilePath;
			}
			set { strategiesInfoFilePath = value; }
		}
		
		public StrategyFileNamer()
		{
		}
	}
}
