/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business\TestSmtpStrategy.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Configuration;
using SoftwareMonkeys.WorkHub.Entities;
using System.Configuration;
using System.Net.Mail;

namespace SoftwareMonkeys.WorkHub.Business
{
	/// <summary>
	/// 
	/// </summary>
	[Strategy("Test", "SMTP")]
	public class TestSmtpStrategy : BaseStrategy
	{
		static public string SmtpServer
		{
			get
			{
				return Emailer.SmtpServer;
			}
		}
		
		public TestSmtpStrategy()
		{
		}
		
		/// <summary>
		/// Sends a test email to the primary administrator to ensure that it works.
		/// </summary>
		/// <param name="smtpServer">The SMTP server to send a test email to.</param>
		/// <returns>A boolean value indicating whether the test succeeded.</returns>
		public bool RunTest()
		{
			return RunTest(SmtpServer);
		}
		
		/// <summary>
		/// Sends a test email to the primary administrator to ensure that it works.
		/// </summary>
		/// <param name="smtpServer">The SMTP server to send a test email to.</param>
		/// <returns>A boolean value indicating whether the test succeeded.</returns>
		public bool RunTest(string smtpServer)
		{
			try
			{
				string systemEmail = Config.Application.Settings.GetString("SystemEmail");
				
				if (systemEmail == null || systemEmail == String.Empty)
					return false;
				
				MailMessage message = new MailMessage(systemEmail,
				                                      systemEmail,
				                                      "Test Email",
				                                      "Test Worked!");

				Emailer.CreateSmtpClient().Send(message);
				
				return true;
			}
			catch (SmtpException)
			{
				return false;
			}
		}
		
		static public TestSmtpStrategy New()
		{
			return new TestSmtpStrategy();
		}
	}
}
