/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\State\Cookies\CookieCrypter.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Web.Security;

namespace SoftwareMonkeys.WorkHub.Web.State.Cookies
{
	public class CookieCrypter
	{
		public CookieCrypter ()
		{
		}
		
		static public string Decrypt(string value)
		{
			FormsAuthenticationTicket ticket = null;
			
			try
			{
				ticket = FormsAuthentication.Decrypt(value);
			}
			catch
			{
				// Ignore and return String.Empty
			}
            
			if (ticket != null)
            			return ticket.UserData;
			else
				return String.Empty;
		}
		
		static public string Encrypt(string name, string value, DateTime expires)
		{
			
			
			FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(1, name, DateTime.Now, expires, false, value, FormsAuthentication.FormsCookiePath);
			
			string encryptedValue = String.Empty;
			
			try
			{
				encryptedValue = FormsAuthentication.Encrypt(ticket);
			}
			catch (ArgumentOutOfRangeException ex)
			{
				throw new ArgumentOutOfRangeException("Invalid expiration date: " + expires.ToString(), ex);
			}
			catch
			{
				// Ignore and return String.Empty
			}
            
            		return encryptedValue;
		}
	}
}

