/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Contracts\Data\FilterGroupOperator.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Collections;

namespace SoftwareMonkeys.WorkHub.Data
{
	/// <summary>
	/// Defines all possible operators for a data filter group.
	/// </summary>
	public enum FilterGroupOperator
	{
		/// <summary>
		/// Indicates that any filter needs to match (not all).
		/// </summary>
		Or,
		/// <summary>
		/// Indicates that all filters need to match (not just any).
		/// </summary>
		And
	}

}
