/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Tests\Entities\ITestRole.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Entities;

namespace SoftwareMonkeys.WorkHub.Tests.Entities
{
    /// <summary>
    /// Defines the interface for a user role in the application.
    /// </summary>
    [Entity]
    public interface ITestRole : IEntity
    {
        string Name { get;set; }
		//IUserPermission[] Permissions { get;set; }
		ITestUser[] Users {get;set;}
		//Guid[] UserIDs {get;set;}
		//void AddUser(IUser user);
		//void RemoveUser(IUser user);
    }
}
