/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Tests\Entities\ITestArticle.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Entities;

namespace SoftwareMonkeys.WorkHub.Tests.Entities
{
	/// <summary>
	/// Description of ITestArticle.
	/// </summary>
	[Entity]
	[Alias("TestArticle")]
	public interface ITestArticle : SoftwareMonkeys.WorkHub.Entities.IEntity
	{
	}
}
