/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Tests\Entities\TestArticle.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Collections.Generic;
using System.Text;
using SoftwareMonkeys.WorkHub.Entities;
using System.Xml.Serialization;
using SoftwareMonkeys.WorkHub.Configuration;

namespace SoftwareMonkeys.WorkHub.Tests.Entities
{
	[Serializable]
    public class TestArticle : BaseUniqueTestEntity, ITestArticle
    {    	
        private string title;
        public string Title
        {
            get { return title; }
            set { title = value;
            	UniqueKey = value;
            }
        }

        private TestCategory[] categories;
        [Reference(MirrorPropertyName="Articles")]
        public TestCategory[] Categories
        {
            get { return categories; }
            set { categories = value; }
        }

        private TestArticlePage[] pages = new TestArticlePage[] { };
        /// <summary>
        /// Gets/sets the associated pages.
        /// </summary>
        [Reference(MirrorPropertyName="Article")]
        //[XmlIgnore()]
        public TestArticlePage[] Pages
        {
            get { return pages; }
            set
            {
                pages = value;
            }
        }

        private TestSample[] samples;
        [Reference(MirrorPropertyName="Articles")]
        public TestSample[] Samples
        {
            get { return samples; }
            set { samples = value; }
        }
        
        private TestUser[] authors;
        [Reference]
        public TestUser[] Authors
        {
            get { return authors; }
            set { authors = value; }
        }
        
        private TestUser[] editors;
        [Reference]
        public TestUser[] Editors
        {
            get { return editors; }
            set { editors = value; }
        }
        
        public override string ToString()
		{
        	return Title;
		}

    }
}
