/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Tests\Entities\TestEnum.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;

namespace SoftwareMonkeys.WorkHub.Tests.Entities
{
	/// <summary>
	/// Description of TestEnum.
	/// </summary>
	public enum TestEnum
	{
		One = 1,
		Two = 2,
		Three = 3
	}
}