/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Tests\Entities\TestRecord.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Entities;
using System.Configuration;
using SoftwareMonkeys.WorkHub.Configuration;

namespace SoftwareMonkeys.WorkHub.Tests.Entities
{
	/// <summary>
	/// Description of TestRecord.
	/// </summary>
	[Serializable]
	public class TestRecord : BaseEntity
	{
		private string name;
		public string Name
		{
			get { return name;  }
			set { name = value; }
		}
		
		private string text;
		public string Text
		{
			get { return text; }
			set { text = value; }
		}
		
		public TestRecord()
		{
		}
		
		 
	}
}
