<%--
====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\WWW\Admin\InitializeCache.aspx

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================

--%>

<%@ Page Language="C#" Title="InitializeCache" %>
<%@ Import Namespace="SoftwareMonkeys.WorkHub.Entities" %>
<%@ Import Namespace="SoftwareMonkeys.WorkHub.Business" %>
<%@ Import Namespace="SoftwareMonkeys.WorkHub.Configuration" %>
<%@ Import Namespace="System.Reflection" %>
<%@ Import Namespace="SoftwareMonkeys.WorkHub.Web" %>
<%@ Import Namespace="SoftwareMonkeys.WorkHub.Web.WebControls" %>
<%@ Import Namespace="SoftwareMonkeys.WorkHub.Web.Security" %>
<%@ Import namespace="System.IO" %>
<%@ Import namespace="System.Xml" %>
<%@ Import namespace="System.Xml.Serialization" %>
<%@ Import namespace="SoftwareMonkeys.WorkHub.Data" %>
<%@ Import namespace="SoftwareMonkeys.WorkHub.Diagnostics" %>
<%@ Import namespace="SoftwareMonkeys.WorkHub.State" %>
<%@ Import namespace="SoftwareMonkeys.WorkHub.Web.Projections" %>
<%@ Import namespace="SoftwareMonkeys.WorkHub.Web.Controllers" %>
<%@ Import namespace="SoftwareMonkeys.WorkHub.Web.Parts" %>
<%@ Import namespace="SoftwareMonkeys.WorkHub.Web.State" %>
<script runat="server">

private void Page_Load(object sender, EventArgs e)
{
	using (TimeoutExtender extender = TimeoutExtender.NewMinutes(30))
	{
		StateProviderInitializer.Initialize();
		
		new EntityInitializer().Initialize();
		new StrategyInitializer().Initialize();
		new ReactionInitializer().Initialize();
		new PartsInitializer(this).Initialize();
		new ControllersInitializer().Initialize();
		new ProjectionsInitializer(this).Initialize();
	}
}
   
</script>
<html>
<head runat="server"></head>
<body>
Cache has been initialized.
</body>
</html>








