<%--
====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\WWW\Admin\PrepareAutoUpdate.aspx

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================

--%>

<%@ Page Language="C#" Title="Prepare Auto Update" autoeventwireup="true" %>
<%@ Register Namespace="SoftwareMonkeys.WorkHub.Web.WebControls" Assembly="SoftwareMonkeys.WorkHub.Web" TagPrefix="cc" %>
<%@ Register Namespace="SoftwareMonkeys.WorkHub.Web.WebControls" Assembly="SoftwareMonkeys.WorkHub.Web" TagPrefix="ss" %>
<%@ Import Namespace="SoftwareMonkeys.WorkHub.Entities" %>
<%@ Import Namespace="SoftwareMonkeys.WorkHub.Business" %>
<%@ Import Namespace="SoftwareMonkeys.WorkHub.Configuration" %>
<%@ Import Namespace="System.Reflection" %>
<%@ Import Namespace="SoftwareMonkeys.WorkHub.Web" %>
<%@ Import Namespace="SoftwareMonkeys.WorkHub.Web.WebControls" %>
<%@ Import namespace="System.IO" %>
<%@ Import namespace="System.Xml" %>
<%@ Import namespace="System.Xml.Serialization" %>
<%@ Import namespace="SoftwareMonkeys.WorkHub.Data" %>
<%@ Import namespace="ICSharpCode.SharpZipLib.Zip" %>
<%@ Import namespace="SoftwareMonkeys.WorkHub.Web.Security" %>
<%@ Import namespace="SoftwareMonkeys.WorkHub.Diagnostics" %>
<script runat="server">
	
    protected void Page_Load(object sender, EventArgs e)
    {
    	if (EnsureAuthorised())    
        	Start();
	}
    
    private void Start()
    {
    	ApplicationBackup backup = new ApplicationBackup();
    	backup.PrepareForUpdate = true;
    	backup.Backup();    	
    }
    
    private bool EnsureAuthorised()
    {
    	string configFile = Server.MapPath(Request.ApplicationPath + "/AllowAutoUpdate.config");
    
    	bool isAuthorised = false;
    
    	using (StreamReader reader = new StreamReader(File.OpenRead(configFile)))
    	{
    		string content = reader.ReadToEnd().Trim();
    		
    		try
    		{
    			isAuthorised = Convert.ToBoolean(content);
    		}
    		catch (Exception ex)
    		{
    			// If there's an error just log it and presume the user is not authorised
    			LogWriter.Error(ex);
    		}
    	}
    	
    	if (!isAuthorised)
    		Authorisation.InvalidPermissionsRedirect();
    		
    	return isAuthorised;
    }

</script>
<html>
<body>
Ready
</body>
</html>
