/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\Controllers\AssemblyContainsControllersAttribute.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;

namespace SoftwareMonkeys.WorkHub.Web.Controllers
{
	/// <summary>
	/// 
	/// </summary>
	[AttributeUsage(AttributeTargets.Assembly)]
	public class AssemblyContainsControllersAttribute : Attribute
	{
		private bool areTestControllers = false;
		public bool AreTestControllers
		{
			get { return areTestControllers; }
			set { areTestControllers = value; }
		}
		
		public AssemblyContainsControllersAttribute()
		{
		}
		
		public AssemblyContainsControllersAttribute(bool areTestControllers)
		{
			AreTestControllers = areTestControllers;
		}
	}
}
