/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\Controllers\BaseControllerScanner.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;

namespace SoftwareMonkeys.WorkHub.Web.Controllers
{
	/// <summary>
	/// The base of all controller scanners. Derivatives can be created to scan different locations or different approaches.
	/// </summary>
	public abstract class BaseControllerScanner
	{
		public BaseControllerScanner()
		{
		}
		
		
		/// <summary>
		/// Finds all the controllers in the available assemblies.
		/// </summary>
		/// <param name="includeTestControllers"></param>
		/// <returns>An array of info about the controllers found.</returns>
		public abstract ControllerInfo[] FindControllers(bool includeTestControllers);
	}
}
