/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\Controllers\ControllersResetter.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.IO;

namespace SoftwareMonkeys.WorkHub.Web.Controllers
{
	/// <summary>
	/// Used to reset the controllers so they can be re-scanned and re-intialized.
	/// </summary>
	public class ControllersResetter
	{
		public ControllersResetter()
		{
		}
		
		public void Reset()
		{
			// Dispose the in-memory state
			new ControllersDisposer().Dispose();
			
			string path = new ControllerFileNamer().ControllersInfoFilePath;
			
			File.Delete(path);
			
			// Now the controllers can be re-scanned and re-initialized
		}
	}
}
