/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\Controllers\DeleteSubEntityController.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Business;
using SoftwareMonkeys.WorkHub.Entities;
using SoftwareMonkeys.WorkHub.Web.Controllers;
using SoftwareMonkeys.WorkHub.Web.Navigation;

namespace SoftwareMonkeys.WorkHub.Web.Controllers
{
	/// <summary>
	/// 
	/// </summary>
	[Controller("Delete", "ISubEntity")]
	public class DeleteSubEntityController : DeleteController
	{
		public DeleteSubEntityController()
		{
		}
		
		public override void ExecuteDelete(IEntity e)
		{
			if (e == null)
				throw new ArgumentNullException("e");
		
			ISubEntity entity = (ISubEntity)e;
			
			if (entity.Parent == null)
				ActivateStrategy.New<ISubEntity>().Activate(entity, entity.ParentPropertyName);
			
			base.ExecuteDelete(entity);
		}
		
		public override void NavigateAfterDelete(IEntity e)
		{
			ISubEntity entity = (ISubEntity)e;
			
			if (entity.Parent == null)
				throw new Exception("No parent has been assigned to sub entity.");
			
			Navigator.Current.NavigateAfterOperation("View", entity.Parent);
		}
	}
}
