/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\Controllers\RegisterUserController.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Entities;
using SoftwareMonkeys.WorkHub.Business;
using SoftwareMonkeys.WorkHub.Business.Security;
using SoftwareMonkeys.WorkHub.Web.Navigation;
using SoftwareMonkeys.WorkHub.Web.Security;
using SoftwareMonkeys.WorkHub.Diagnostics;
using SoftwareMonkeys.WorkHub.Configuration;

namespace SoftwareMonkeys.WorkHub.Web.Controllers
{
	/// <summary>
	/// 
	/// </summary>
	[Controller("Register", "User")]
	public class RegisterUserController : CreateUserController
	{
		public RegisterUserController()
		{
			ActionOnSuccess = "Details";
		}
		
		public override bool ExecuteSave(User user)
		{
			bool success = false;
			
			using (LogGroup logGroup = LogGroup.Start("Saving the new user.", NLog.LogLevel.Debug))
			{
				LogWriter.Debug("Auto navigate: " + AutoNavigate.ToString());
				
				// Cancel the base automatic navigation
				AutoNavigate = false;
				
				success = base.ExecuteSave(user); // Base function should take care of encrypting password etc
				
				LogWriter.Debug("Success: " + success.ToString());
				
				if (success)
				{
					LogWriter.Debug("Is approved: " + user.IsApproved.ToString());
					
					LogWriter.Debug("Signing the new user in.");
					
					// Only sign the user in and send them to their account page if the user was automatically approvied (based on settings)
					if (user.IsApproved)
					{
						Authentication.SetAuthenticatedUsername(user.Username);
						
						NavigateAfterSave();
					}
					
				}
				else
				{
					LogWriter.Debug("Failed to save (username in use).");
				}
			}
			
			return success;
		}
		
		public override void NavigateAfterSave()
		{
			if (((User)DataSource).IsApproved)
				Navigator.Current.Go("Details", "User");
		}
	}
}
