/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Entities.Tests\BaseEntityTestFixture.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using NUnit.Framework;
using SoftwareMonkeys.WorkHub.Configuration.Tests;
using SoftwareMonkeys.WorkHub.Tests.Entities;
using System.IO;
using System.Reflection;

namespace SoftwareMonkeys.WorkHub.Entities.Tests
{
	/// <summary>
	/// The base of all entity test fixtures.
	/// </summary>
	public class BaseEntityTestFixture : BaseConfigurationTestFixture
	{
		[SetUp]
		public override void Start()
		{
			base.Start();
			
			InitializeMockEntities();
		}
		
		[TearDown]
		public override void End()
		{
			DisposeMockEntities();
			
			base.End();
		}
		
		
		protected virtual void InitializeMockEntities()
		{
			string testsAssemblyPath = Assembly.Load("SoftwareMonkeys.WorkHub.Tests").Location;
			string entitiesTestsAssemblyPath = Assembly.Load("SoftwareMonkeys.WorkHub.Entities.Tests").Location;
			
			string[] assemblyPaths = new String[] {testsAssemblyPath,
				entitiesTestsAssemblyPath};
			
			EntityInitializer initializer = new EntityInitializer();
			
			// Set the specific assemblies used during testing as it can't do it automatically in the mock environment
			initializer.Scanner.AssemblyPaths = assemblyPaths;
			
			initializer.Initialize(true);
		}
		
		protected void DisposeMockEntities()
		{
			EntityState.Entities = null;
		}
	}
}
