/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Entities.Tests\EntityStateTests.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using NUnit.Framework;
using SoftwareMonkeys.WorkHub.Tests.Entities;

namespace SoftwareMonkeys.WorkHub.Entities.Tests
{
	/// <summary>
	/// 
	/// </summary>
	[TestFixture]
	public class EntityStateTests : BaseEntityTestFixture
	{
		[Test]
		public void Test_GetType_FullName()
		{
			Type type = EntityState.GetType(typeof(TestRecord).FullName + ", " + typeof(TestRecord).Assembly.GetName().Name);
			
			Assert.IsNotNull(type, "Type is null");
			
			Assert.AreEqual(typeof(TestRecord).FullName, type.FullName, "Doesn't match expected.");
		}
		
		[Test]
		public void Test_GetType_ShortName()
		{
			Type type = EntityState.GetType(typeof(TestRecord).Name);
			
			Assert.IsNotNull(type, "Type is null");
			
			Assert.AreEqual(typeof(TestRecord).FullName, type.FullName, "Doesn't match expected.");
		}
		
		[Test]
		public void Test_GetInfo_FullName()
		{
			EntityInfo info = EntityState.GetInfo(typeof(TestRecord).FullName + ", " + typeof(TestRecord).Assembly.GetName().Name);
			
			Assert.IsNotNull(info, "info is null");
			
			Assert.AreEqual(typeof(TestRecord).FullName + ", " + typeof(TestRecord).Assembly.GetName().Name,
			                info.FullType, "Doesn't match expected.");
		}
		
		[Test]
		public void Test_GetInfo_ShortName()
		{
			EntityInfo info = EntityState.GetInfo(typeof(TestRecord).Name);
			
			Assert.IsNotNull(info, "info is null");
			
			Assert.AreEqual(typeof(TestRecord).FullName + ", " + typeof(TestRecord).Assembly.GetName().Name,
			                info.FullType, "Doesn't match expected.");
		}
	}
}
