/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business.Tests\BaseBusinessTestFixture.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Data.Tests;
using SoftwareMonkeys.WorkHub.Diagnostics;
using SoftwareMonkeys.WorkHub.Entities.Tests;
using SoftwareMonkeys.WorkHub.Entities;
using NUnit.Framework;
using System.Reflection;

namespace SoftwareMonkeys.WorkHub.Business.Tests
{
	public class BaseBusinessTestFixture : BaseDataTestFixture
	{
		public bool EnableBusinessState = true;
		
		[SetUp]
		public override void Start()
		{
			base.Start();
			
			InitializeMockBusiness();
		}
		
		[TearDown]
		public override void End()
		{
			DisposeMockBusiness();
			
			base.End();
		}
		
		public BaseBusinessTestFixture()
		{
			
		}
		
		protected override void InitializeMockEntities()
		{
			string testsAssemblyPath = Assembly.Load("SoftwareMonkeys.WorkHub.Tests").Location;
			string entitiesAssemblyPath = Assembly.Load("SoftwareMonkeys.WorkHub.Entities").Location;
			string entitiesTestsAssemblyPath = Assembly.Load("SoftwareMonkeys.WorkHub.Entities.Tests").Location;
			string businessTestsAssemblyPath = Assembly.Load("SoftwareMonkeys.WorkHub.Business.Tests").Location;
			
			string[] assemblyPaths = new String[] {testsAssemblyPath, entitiesAssemblyPath, entitiesTestsAssemblyPath, businessTestsAssemblyPath};
			
			EntityInitializer initializer = new EntityInitializer();
			
			// Set the specific assemblies used during testing as it can't do it automatically in the mock environment
			initializer.Scanner.AssemblyPaths = assemblyPaths;
			
			initializer.Initialize(true);
		}
		
		public virtual void InitializeMockBusiness()
		{
			using (LogGroup logGroup = LogGroup.StartDebug("Initializing mock business tier."))
			{
				if (EnableBusinessState)
				{
					string businessAssemblyPath = Assembly.Load("SoftwareMonkeys.WorkHub.Business").Location;
					string businessTestsAssemblyPath = Assembly.Load("SoftwareMonkeys.WorkHub.Business.Tests").Location;
					
					string[] assemblyPaths = new String[]
					{
						businessAssemblyPath,
						businessTestsAssemblyPath
					};
					
					// Strategies
					
					StrategyInitializer initializer = new StrategyInitializer();
					
					// Set the specific assemblies used during testing as it can't do it automatically in the mock environment
					initializer.Scanner.AssemblyPaths = assemblyPaths;
					
					initializer.Initialize(true);
					
					
					// Reactions
					
					ReactionInitializer reactionsInitializer = new ReactionInitializer();
					
					// Set the specific assemblies used during testing as it can't do it automatically in the mock environment
					reactionsInitializer.Scanner.AssemblyPaths = assemblyPaths;
					
					reactionsInitializer.Initialize(true);
				}
			}
		}
		
		public void DisposeMockBusiness()
		{
			StrategyState.Strategies = null;
			ReactionState.Reactions = null;
		}
		
		public override void InitializeMockData()
		{
			new MockDb4oDataProviderInitializer(this).Initialize();
		}
	}
}
