/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business.Tests\DeleteStrategyTests.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using NUnit.Framework;
using SoftwareMonkeys.WorkHub.Tests.Entities;
using SoftwareMonkeys.WorkHub.Business;

namespace SoftwareMonkeys.WorkHub.Business.Tests
{
	[TestFixture]
	public class DeleteStrategyTests : BaseBusinessTestFixture
	{
		[Test]
		public void Test_Delete()
		{
			
			TestArticle article = new TestArticle();
			article.ID = Guid.NewGuid();
			
			IDeleteStrategy strategy = DeleteStrategy.New<TestArticle>(false);
			
			Data.DataAccess.Data.Saver.Save(article);
			
			TestArticle foundArticle = Data.DataAccess.Data.Reader.GetEntity<TestArticle>("ID", article.ID);
			
			Assert.IsNotNull(foundArticle);
			
			strategy.Delete(article);
			
			TestArticle foundArticle2 = Data.DataAccess.Data.Reader.GetEntity<TestArticle>("ID", article.ID);
			
			Assert.IsNull(foundArticle2, "The article wasn't deleted.");
		}
	}
}
