/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business.Tests\DualStrategyTests.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using NUnit.Framework;
using SoftwareMonkeys.WorkHub.Business;

namespace SoftwareMonkeys.WorkHub.Business.Tests
{
	/// <summary>
	/// 
	/// </summary>
	[TestFixture]
	public class DualStrategyTests : BaseBusinessTestFixture
	{
		public DualStrategyTests()
		{
		}
		
		[Test]
		public void Test_Found()
		{
			Assert.IsNotNull(StrategyState.Strategies["MockAction1", "MockNonEntity1"], "Didn't detect first strategy attribute.");
			
			Assert.IsNotNull(StrategyState.Strategies["MockAction2", "MockNonEntity2"], "Didn't detect second strategy attribute.");
		}
	}
}
