/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business.Tests\MockSaveTestArticleReaction.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Business;
using SoftwareMonkeys.WorkHub.Entities;
using SoftwareMonkeys.WorkHub.State;

namespace SoftwareMonkeys.WorkHub.Business.Tests
{
	/// <summary>
	/// 
	/// </summary>
	[Reaction("Save", "TestArticle")]
	public class MockSaveTestArticleReaction : BaseReaction
	{
		public MockSaveTestArticleReaction()
		{
		}
		
		public override void React(IEntity entity)
		{
			StateAccess.State.Session["MockSaveTestArticleReaction_Reacted"] = true;
		}
	}
}
