/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business.Tests\MockNonEntityStrategy.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;

namespace SoftwareMonkeys.WorkHub.Business.Tests
{
	/// <summary>
	/// 
	/// </summary>
	[Strategy("MockAction", "NonEntity")]
	public class MockNonEntityStrategy : BaseStrategy
	{
		public MockNonEntityStrategy()
		{
		}
	}
}
