/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business.Tests\MockSaveTestArticleStrategy.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Data;
using SoftwareMonkeys.WorkHub.Entities;

namespace SoftwareMonkeys.WorkHub.Business.Tests
{
	/// <summary>
	/// 
	/// </summary>
	[Strategy("Save", "TestArticle")]
	public class MockSaveTestArticleStrategy : SaveStrategy
	{
		public MockSaveTestArticleStrategy()
		{
		}
		
		public override bool Save(IEntity entity)
		{
			return base.Save(entity);
		}
		
		static public MockSaveTestArticleStrategy New()
		{
			return New(true);
		}
		
		static public MockSaveTestArticleStrategy New(bool requiresAuthorisation)
		{
			MockSaveTestArticleStrategy strategy = new MockSaveTestArticleStrategy();
			strategy.TypeName = "TestArticle";
			strategy.RequireAuthorisation = requiresAuthorisation;
			
			StrategyState
				.Strategies
				.Creator
				.AttachReactions("Save", strategy);
			
			return strategy;
		}
	}
}
