/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business.Tests\MockValidateInvalidStrategy.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;

namespace SoftwareMonkeys.WorkHub.Business.Tests
{
	/// <summary>
	/// Used to test a validation failure.
	/// </summary>
	[ValidateStrategy("MockInvalid", "IEntity")]
	public class MockValidateInvalidStrategy : BaseValidatePropertyStrategy
	{
		public MockValidateInvalidStrategy()
		{
		}
		
		public override bool IsValid(SoftwareMonkeys.WorkHub.Entities.IEntity entity, System.Reflection.PropertyInfo property, SoftwareMonkeys.WorkHub.Entities.IValidatePropertyAttribute attribute)
		{
			return false;
		}
	}
}
