/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business.Tests\ValidateRequiredStrategyTests.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Reflection;
using NUnit.Framework;
using SoftwareMonkeys.WorkHub.Entities;
using SoftwareMonkeys.WorkHub.Entities.Tests.Entities;

namespace SoftwareMonkeys.WorkHub.Business.Tests
{
	/// <summary>
	///
	/// </summary>
	[TestFixture]
	public class ValidateRequiredStrategyTests : BaseBusinessTestFixture
	{
		[Test]
		public void Test_IsValid_False_String()
		{
			MockRequiredEntity entity = new MockRequiredEntity();
			
			ValidateRequiredStrategy strategy = new ValidateRequiredStrategy();
			
			PropertyInfo property = entity.GetType().GetProperty("TestProperty");
			
			object[] objs = property.GetCustomAttributes(typeof(RequiredAttribute), true);
			
			IValidatePropertyAttribute attribute = (IValidatePropertyAttribute)objs[0];
			
			bool isValid = strategy.IsValid(entity, property, attribute);
			
			Assert.IsFalse(isValid, "Returned true when it should have been false.");
		}
		
		[Test]
		public void Test_IsValid_True_String()
		{
			MockRequiredEntity entity = new MockRequiredEntity();
			entity.TestProperty = "TestValue";
			
			ValidateRequiredStrategy strategy = new ValidateRequiredStrategy();
			
			PropertyInfo property = entity.GetType().GetProperty("TestProperty");
			
			object[] objs = property.GetCustomAttributes(typeof(RequiredAttribute), true);
			
			IValidatePropertyAttribute attribute = (IValidatePropertyAttribute)objs[0];
			
			bool isValid = strategy.IsValid(entity, property, attribute);
			
			Assert.IsTrue(isValid, "Returned false when it should have been true.");
		}
	}
}
