/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web.Tests\WebControls\EntitySelectTests.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using NUnit.Framework;
using SoftwareMonkeys.WorkHub.Business;
using SoftwareMonkeys.WorkHub.Entities;
using SoftwareMonkeys.WorkHub.Tests.Entities;
using SoftwareMonkeys.WorkHub.Web.WebControls;

namespace SoftwareMonkeys.WorkHub.Web.Tests.WebControls
{
	/// <summary>
	/// 
	/// </summary>
	[TestFixture]
	public class EntitySelectTests : BaseWebTestFixture
	{
		/// <summary>
		/// Tests the GetPostEntities function when AutoLoadPostEntities property is true.
		/// </summary>
		[Test]
		public void Test_GetPostedEntities_AutoLoadPostEntitiesTrue()
		{
			TestRecord record = new TestRecord();
			record.ID = Guid.NewGuid();
			
			EntitySelect<TestRecord> ctrl = new EntitySelect<TestRecord>();
			ctrl.AutoLoadPostEntities = true;			
			ctrl.EntityType = record.GetType().FullName + ", " + typeof(TestRecord).Assembly.GetName().Name;
			ctrl.RequireAuthorisation = false; // Only false during testing
			
			Guid[] ids = new Guid[] { record.ID };
			
			SaveStrategy.New(record, false).Save(record);
			
			IEntity[] entities = ctrl.GetPostedEntities(ids);
			
			Assert.IsNotNull(entities, "Returned null");
			
			// The entity should have been loaded automatically
			Assert.AreEqual(1, entities.Length, "Invalid number of entities returned.");
		}
		
		/// <summary>
		/// Tests the GetPostEntities function when AutoLoadPostEntities property is false.
		/// </summary>
		[Test]
		public void Test_GetPostedEntities_AutoLoadPostEntitiesFalse()
		{
			TestRecord record = new TestRecord();
			record.ID = Guid.NewGuid();
			
			EntitySelect<TestRecord> ctrl = new EntitySelect<TestRecord>();
			ctrl.AutoLoadPostEntities = false;				
			ctrl.EntityType = record.GetType().FullName + ", " + typeof(TestRecord).Assembly.GetName().Name;
			ctrl.RequireAuthorisation = false; // Only false during testing
			
			Guid[] ids = new Guid[] { record.ID };
			
			SaveStrategy.New(record, false).Save(record);
			
			IEntity[] entities = ctrl.GetPostedEntities(ids);
			
			Assert.IsNotNull(entities, "Returned null");
			
			// No entities should be returned because they weren't found on DataSource
			Assert.AreEqual(0, entities.Length, "Invalid number of entities returned.");
		}
	}
}
