<%--
====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\WWW\AutoBackup.aspx

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================

--%>

<%@ Page Language="C#" AutoEventWireup="true" %>
<%@ Import namespace="SoftwareMonkeys.WorkHub.Web" %>
<script runat="server">
private void Page_Load(object sender, EventArgs e)
{
	new AutoBackupExecutor().Initialize();
}
</script>
<html>
<body>
</body>
</html>