/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Data\IDataSchemaCommand.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Xml;

namespace SoftwareMonkeys.WorkHub.Data
{
	/// <summary>
	/// Defines the interface required by all schema edit commands.
	/// </summary>
	public interface IDataSchemaCommand
	{
		/// <summary>
		/// Gets/sets the short name of the corresponding type.
		/// </summary>
		string TypeName {get;set;}
		
		/// <summary>
		/// Checks whether the command applies to the type serialized in the provided XML document.
		/// </summary>
		/// <param name="document">A serialized entity as an XML document.</param>
		/// <returns>A boolean flag indicating whether or not the command applies to the specified type.</returns>
		bool AppliesTo(XmlDocument document);
		
		/// <summary>
		/// Executes the commands and applies the effects to the provided XML document.
		/// </summary>
		/// <param name="document">The entity serialized and loaded into an XML document.</param>
		void Execute(XmlDocument document);
	}
}
