/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Data\IDataSaver.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Entities;

namespace SoftwareMonkeys.WorkHub.Data
{
	/// <summary>
	/// 
	/// </summary>
	public interface IDataSaver : IDataAdapter
	{		
		void Save(IEntity entity);
		
		void Save(IEntity entity, bool handleReferences);
		
		void PreSave(IEntity entity, bool handleReferences);
		
	}
}
