/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Entities\AssemblyContainsEntitiesAttribute.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;

namespace SoftwareMonkeys.WorkHub.Entities
{
	/// <summary>
	/// 
	/// </summary>
	[AttributeUsage(AttributeTargets.Assembly)]
	public class AssemblyContainsEntitiesAttribute : Attribute
	{
		private bool areTestEntities = false;
		/// <summary>
		/// Gets/sets a flag indicating whether the entities in this assembly are test/mock entities.
		/// </summary>
		public bool AreTestEntities
		{
			get  { return areTestEntities; }
			set  { areTestEntities = value; }
		}
		
		public AssemblyContainsEntitiesAttribute()
		{
		}
		
		public AssemblyContainsEntitiesAttribute(bool areTestEntities)
		{
			AreTestEntities = areTestEntities;
		}
	}
}
