/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Entities\AssemblyScanInfo.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using SoftwareMonkeys.WorkHub.Entities;

// Mark the assembly as containing entities so that it will get scanned by the entity scanner.
[assembly: AssemblyContainsEntities()]

