/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Entities\EntityFileNamer.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.IO;
using SoftwareMonkeys.WorkHub.State;

namespace SoftwareMonkeys.WorkHub.Entities
{
	/// <summary>
	/// Used to create file names/paths for entity components.
	/// </summary>
	public class EntityFileNamer
	{
		private string entitiesInfoFilePath;
		/// <summary>
		/// Gets the path to the file containing the entity info.
		/// </summary>
		public virtual string EntitiesInfoFilePath
		{
			get {
				if (entitiesInfoFilePath == null || entitiesInfoFilePath == String.Empty)
				{
					if (StateAccess.IsInitialized)
						entitiesInfoFilePath = StateAccess.State.PhysicalApplicationPath
							+ Path.DirectorySeparatorChar + "App_Data"
							+ Path.DirectorySeparatorChar + "Entities.xml";
				}
				return entitiesInfoFilePath;
			}
			set { entitiesInfoFilePath = value; }
		}
		
		public EntityFileNamer()
		{
		}
	}
}
