/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Entities\RequiredAttribute.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;

namespace SoftwareMonkeys.WorkHub.Entities
{
	/// <summary>
	/// Indicates that the corresponding property is required to have a value.
	/// </summary>
	[AttributeUsage(AttributeTargets.Property)]
	[Serializable]
	public class RequiredAttribute : BaseValidatePropertyAttribute
	{
		public RequiredAttribute()
		{
			ValidatorName = "Required";
		}
	}
}
