/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Entities\SortDirection.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;

namespace SoftwareMonkeys.WorkHub.Entities
{
	/// <summary>
	/// Enumerates the directions available for sorting.
	/// </summary>
	public enum SortDirection
	{
		/// <summary>
		/// Forwards, from A-Z or 1-9.
		/// </summary>
		Ascending = 1,
		/// <summary>
		/// Backwards, from Z-A or 9-1
		/// </summary>
		Descending = 2
	}
}
