/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Entities\UserRole.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Configuration;
using System.Collections.Generic;

namespace SoftwareMonkeys.WorkHub.Entities
{
    /// <summary>
    /// Defines the interface for a user role in the application.
    /// </summary>
    [Serializable]
    [Entity]
    public class UserRole : BaseUniqueEntity, IUserRole
    {
        private string name;
        /// <summary>
        /// Gets/sets the name of the role.
        /// </summary>
		[Required]
		[Unique]
        public string Name
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
                UniqueKey = value;
            }
        }

        private User[] users;
        /// <summary>
        /// Gets/sets the users to this role.
        /// </summary>
        [Reference(MirrorPropertyName="Roles",
                  CountPropertyName="TotalUsers")]
        public User[] Users
        {
            get {
        		if (users == null)
        			users = new User[]{};
        		return users; }
            set
            {
            	users = value;
            }
        }        
        
        private int totalUsers;
        /// <summary>
        /// Gets/sets the total number of users assigned to the role.
        /// </summary>
        public int TotalUsers
        {
        	get { return totalUsers; }
        	set { totalUsers = value; }
        }

        IUser[] IUserRole.Users
        {
        	get { return Collection<IUser>.ConvertAll(users); }
        	set { users = Collection<User>.ConvertAll(value); }
        }
        
        public UserRole()
        {
        }
        
        public UserRole(Guid id) : base(id)
        {
        	
        }
   
		public override string ToString()
		{
			return Name;
		}
		
		string ISimple.Title{
			get { return Name; }
			set { Name = value; }
		}
		
		string ISimple.Description{
			get {  return String.Empty; }
			set { }
		}
    }
}