/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web.Tests\Projections\MockEditProjection.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Business;
using SoftwareMonkeys.WorkHub.Web.Projections;

namespace SoftwareMonkeys.WorkHub.Web.Tests.Projections
{
	/// <summary>
	/// 
	/// </summary>
	public class MockEditProjection : BaseProjection
	{
		public MockEditProjection(Type entityType)
		{
			Command = new EditCommandInfo(entityType.Name);
		}
	}
}
