/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web.Tests\Projections\ProjectionStateNameValueTests.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Web.Projections;
using SoftwareMonkeys.WorkHub.Web.Tests;
using NUnit.Framework;

namespace SoftwareMonkeys.WorkHub.Web.Tests.Projections
{
	/// <summary>
	/// Description of ProjectionStateNameValueTests.
	/// </summary>
	[TestFixture]
	public class ProjectionStateNameValueTests : BaseWebTestFixture
	{
		public ProjectionStateNameValueTests()
		{
		}
		
		[Test]
		public void Test_Contains_NameProperty_ActionAndTypeBased()
		{
			ProjectionInfo info = new ProjectionInfo();
			info.TypeName = "TestType";
			info.Action = "TestAction";
			info.Name = "TestType-TestAction";
			info.Format = ProjectionFormat.Html;
			
			ProjectionStateCollection collection = new ProjectionStateCollection();
			collection.Add(info);
			
			Assert.IsTrue(collection.Contains(info.Name), "Returned false when it have been true.");
			
		}
		
		[Test]
		public void Test_Contains_NameProperty_NameBased()
		{
			ProjectionInfo info = new ProjectionInfo();
			info.Name = "TestProjection";
			info.Format = ProjectionFormat.Html;
			
			ProjectionStateCollection collection = new ProjectionStateCollection();
			collection.Add(info);
			
			Assert.IsTrue(collection.Contains(info.Name), "Returned false when it have been true.");
			
		}
		
		[Test]
		public void Test_thisProperty_NameParameter()
		{
			ProjectionInfo info = new ProjectionInfo();
			info.Name = "TestProjection";
			info.Format = ProjectionFormat.Html;
			
			ProjectionStateCollection collection = new ProjectionStateCollection();
			collection[info.Name, info.Format] = info;
			
			Assert.IsTrue(collection.Contains(info.Name), "Returned false when it have been true.");
			
		}
	}
}
