/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\Elements\BaseElement.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Business;
using SoftwareMonkeys.WorkHub.Business.Security;
using SoftwareMonkeys.WorkHub.Entities;
using System.Web.UI.WebControls;
using System.Collections.Generic;
using System.Web.UI;
using System.Web;
using SoftwareMonkeys.WorkHub.Web.WebControls;
using System.Reflection;
using SoftwareMonkeys.WorkHub.Web.Properties;
using SoftwareMonkeys.WorkHub.Diagnostics;
using SoftwareMonkeys.WorkHub.Web.Security;

namespace SoftwareMonkeys.WorkHub.Web.Elements
{
	/// <summary>
	/// 
	/// </summary>
	public abstract class BaseElement : WebControl, IElement
	{		
		private string elementName = String.Empty;
		public string ElementName
		{
			get { return elementName; }
			set { elementName = value; }
		}
		
		private string action = String.Empty;
		/// <summary>
		/// Gets/sets the action being performed.
		/// </summary>
		public virtual string Action
		{
			get
			{
				return action;
			}
			set
			{
				action = value;
			}
		}
		
		private string typeName = String.Empty;
		/// <summary>
		/// Gets/sets the action that is performed once the element is successful.
		/// </summary>
		public string TypeName
		{
			get { return typeName; }
			set { typeName = value; }
		}
		
		Unit IElement.Width
		{
			get { return base.Width; }
			set { base.Width = value; }
		}
		
		public BaseElement()
		{
			
		}
	}
}
