/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\Elements\ElementsResetter.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.IO;

namespace SoftwareMonkeys.WorkHub.Web.Elements
{
	/// <summary>
	/// Used to reset the elements so they can be re-scanned and re-intialized.
	/// </summary>
	public class ElementsResetter
	{
		public ElementsResetter()
		{
		}
		
		public void Reset()
		{
			// Dispose the in-memory state
			new ElementsDisposer().Dispose();
			
			// Delete element info (not the actual elements)
			File.Delete(new ElementFileNamer().ElementsInfoFilePath);
			
			// Now the elements can be re-scanned and re-initialized
		}
	}
}
