/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\Elements\IElement.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Web.UI.WebControls;

namespace SoftwareMonkeys.WorkHub.Web.Elements
{
	/// <summary>
	/// Defines the interface of all web elements.
	/// </summary>
	public interface IElement
	{
		string TypeName {get;set;}
		string Action {get;}
		string ElementName { get; }
		Unit Width { get;set; }
	}
}
