/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\Parts\\PartsDisposer.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Web.UI;
using SoftwareMonkeys.WorkHub.State;
using SoftwareMonkeys.WorkHub.Diagnostics;
using System.IO;

namespace SoftwareMonkeys.WorkHub.Web.Parts
{
	/// <summary>
	/// Used to remove/dispose parts from the system.
	/// </summary>
	public class PartsDisposer
	{
		
		private PartFileNamer fileNamer;
		/// <summary>
		/// Gets/sets the file namer used to create part file names/paths.
		/// </summary>
		public PartFileNamer FileNamer
		{
			get {
				if (fileNamer == null)
					fileNamer = new PartFileNamer();
				return fileNamer; }
			set { fileNamer = value; }
		}
		
		
		public PartsDisposer()
		{
		}
		
		/// <summary>
		/// Disposes the parts found by the scanner.
		/// </summary>
		public void Dispose()
		{
			using (LogGroup logGroup = LogGroup.Start("Disposing the parts.", NLog.LogLevel.Debug))
			{
				Dispose(PartState.Parts.ToArray());
			}
		}
		
		/// <summary>
		/// Disposes the provided parts.
		/// </summary>
		public void Dispose(PartInfo[] parts)
		{
			using (LogGroup logGroup = LogGroup.Start("Disposing the parts.", NLog.LogLevel.Debug))
			{
				foreach (PartInfo part in parts)
				{
					PartState.Parts.Remove(
						PartState.Parts[part.Key]
					);
				}
			}
		}
	}
}
