/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\Parts\\PartsResetter.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.IO;

namespace SoftwareMonkeys.WorkHub.Web.Parts
{
	/// <summary>
	/// Used to reset the parts so they can be re-scanned and re-intialized.
	/// </summary>
	public class PartsResetter
	{
		public PartsResetter()
		{
		}
		
		public void Reset()
		{
			// Dispose the in-memory state
			new PartsDisposer().Dispose();
			
			string file = new PartFileNamer().PartsInfoFilePath;
			
			// Delete part info (not the actual parts)
			File.Delete(file);
			
			// Now the parts can be re-scanned and re-initialized
		}
	}
}
