/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\Projections\\BaseDeleteProjection.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Web.Controllers;
using SoftwareMonkeys.WorkHub.Business;
using SoftwareMonkeys.WorkHub.Entities;
using SoftwareMonkeys.WorkHub.Web.WebControls;
using System.Web.UI.WebControls;
using SoftwareMonkeys.WorkHub.Diagnostics;

namespace SoftwareMonkeys.WorkHub.Web.Projections
{
	/// <summary>
	/// The based of all standard projections used to delete an entity.
	/// </summary>
	public class BaseDeleteProjection : BaseProjection
	{
		
		
		private DeleteController controller;
		/// <summary>
		/// Gets the controller used for deleting an entity.
		/// </summary>
		public DeleteController Controller
		{
			get {
				return controller; }
		}
		
		public BaseDeleteProjection()
		{
		}
		
		protected override void OnLoad(EventArgs e)
		{
			Delete();
			
			base.OnLoad(e);
		}
		
		public void Initialize(Type type)
		{
			Command = new DeleteCommandInfo(type.Name);
			
			controller = DeleteController.New(this, type);
		}
		
		public virtual void Delete()
		{
			using (LogGroup logGroup = LogGroup.Start("Deleting the entity specified in the query string.", NLog.LogLevel.Debug))
			{
				Controller.Delete();
			}
		}
		
		public virtual void Delete(IEntity entity)
		{
			using (LogGroup logGroup = LogGroup.Start("Deleting the entity provided.", NLog.LogLevel.Debug))
			{
				Controller.Delete(entity);
			}
		}
		
	}
}
