/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\Projections\\ProjectionsResetter.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.IO;
using System.Web.UI;
using SoftwareMonkeys.WorkHub.Diagnostics;

namespace SoftwareMonkeys.WorkHub.Web.Projections
{
	/// <summary>
	/// Used to reset the projections so they can be re-scanned and re-intialized.
	/// </summary>
	public class ProjectionsResetter
	{
		public Page Page;
		
		public ProjectionsResetter(Page page)
		{
			Page = page;
		}
		
		public void Reset()
		{
			using (LogGroup logGroup = LogGroup.StartDebug("Resetting projections cache."))
			{
				// Dispose the in-memory state
				new ProjectionsDisposer().Dispose();
				
				// Delete projection info (not the actual projections)
				File.Delete(new ProjectionFileNamer().ProjectionsInfoFilePath);				
			}
		}
	}
}
