/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\Projections\\ProjectionState.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.State;
using SoftwareMonkeys.WorkHub.Web.Projections;

namespace SoftwareMonkeys.WorkHub.Web.Projections
{
	/// <summary>
	/// Holds the current state of the available projections.
	/// </summary>
	public class ProjectionState
	{
		/// <summary>
		/// Gets a value indicating whether the projection state has been initialized.
		/// </summary>
		static public bool IsInitialized
		{
			get { return projections != null && projections.Count > 0; }
		}
		
		static private ProjectionStateCollection projections;
		/// <summary>
		/// Gets/sets a collection of all the available strategies which are held in state.
		/// </summary>
		static public ProjectionStateCollection Projections
		{
			get {
				projections = GetProjections(true);
				return projections;  }
			set { projections = value; }
		}
		
		static public ProjectionStateCollection GetProjections(bool errorIfNotInitialized)
		{
				if (!IsInitialized && errorIfNotInitialized)
					throw new InvalidOperationException("The projection state has not been initialized.");
				
				// If the projections aren't initialized then create an empty collection
				if (projections == null)
					projections = new ProjectionStateCollection();
				
				return projections;
		}
	}
}
