/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\Projections\\ProjectionNotFoundException.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;

namespace SoftwareMonkeys.WorkHub.Web.Projections
{
	/// <summary>
	/// Indicates that a projection for the provided type and action could not be found.
	/// </summary>
	public class ProjectionNotFoundException : ApplicationException
	{
		private string action = String.Empty;
		/// <summary>
		/// Gets/sets the action being performed by the projection.
		/// </summary>
		public string Action
		{
			get { return action; }
			set { action = value; }
		}
		
		private string typeName = String.Empty;
		/// <summary>
		/// Gets/sets the name of the type involved in the projection.
		/// </summary>
		public string TypeName
		{
			get { return typeName; }
			set { typeName = value; }
		}
		
		private string name = String.Empty;
		/// <summary>
		/// Gets/sets the name of the projction.
		/// </summary>
		public string Name
		{
			get { return name; }
			set { name = value; }
		}
		
		private ProjectionFormat format = ProjectionFormat.Html;
		/// <summary>
		/// Gets/sets the format of the projection output.
		/// </summary>
		public ProjectionFormat Format
		{
			get { return format; }
			set { format = value; }
		}
		
		public ProjectionNotFoundException(string name, ProjectionFormat format) : base("A projection could not be found with the name '" + name + "' and output format '" + format + "'.")
		{
			Name = name;
			Format = format;
		}
		
		public ProjectionNotFoundException(string action, string typeName, ProjectionFormat format) : base("A projection could not be found to carry out action '" + action + "', entity type '" + typeName + "' and output format '" + format + "'.")
		{
			Action = action;
			TypeName = typeName;
			Format = format;
		}
	}
}
