/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Data.Tests\DataExporterTests.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using NUnit.Framework;
using SoftwareMonkeys.WorkHub.Data;
using SoftwareMonkeys.WorkHub.Tests.Entities;
using System.Web;
using System.IO;
using SoftwareMonkeys.WorkHub.Tests;
using SoftwareMonkeys.WorkHub.Entities;

namespace SoftwareMonkeys.WorkHub.Data.Tests
{
	[TestFixture]
	public class DataExporterTests : BaseDataTestFixture
	{
		
		/// <summary>
		/// Tests the DataExporter.ExportToXml function while exporting all data.
		/// </summary>
		[Test]
		public void Test_ExportToXml()
		{
			
			TestUser user = new TestUser();
			user.ID = Guid.NewGuid();
			user.FirstName = "Test";
			user.LastName = "Test";
			
			DataAccess.Data.Saver.Save(user);
			
			TestRole role = new TestRole();
			role.ID = Guid.NewGuid();
			role.Name = "Test Role";
			
			DataAccess.Data.Saver.Save(role);
			
			TestArticle article = new TestArticle();
			article.ID = Guid.NewGuid();
			article.Title = "Test";
			
			DataAccess.Data.Saver.Save(article);
			
			TestCategory category = new TestCategory();
			category.Name = "Test";
			
			DataAccess.Data.Saver.Save(category);
			
			string outputDirectory = TestUtilities.GetTestingPath(this) + Path.DirectorySeparatorChar + "Exported";
			
			int expectedCount = 0;
			
			foreach (string dataStoreName in DataAccess.Data.GetDataStoreNames())
			{
				foreach (IEntity entity in DataAccess.Data.Stores[dataStoreName].Indexer.GetEntities())
					expectedCount ++;
			}
			
			DataExporter exporter = (DataExporter)DataAccess.Data.InitializeDataExporter();
			exporter.ExportDirectoryPath = outputDirectory;
						
			exporter.ExportToXml();
			
			Assert.IsTrue(Directory.Exists(outputDirectory), "The output directory doesn't exist.");
			
			int fileCount = 0;
			foreach (string directory in Directory.GetDirectories(outputDirectory))
			{
				foreach (String file in Directory.GetFiles(directory))
				{
					fileCount++;
				}
			}
			
			Assert.AreEqual(expectedCount, fileCount, "Incorrect number of files found.");
			
		}
	}
}
