/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Data.Tests\FilterTests.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Data;
using NUnit.Framework;
using SoftwareMonkeys.WorkHub.Diagnostics;
using SoftwareMonkeys.WorkHub.Tests.Entities;
using SoftwareMonkeys.WorkHub.Entities;

namespace SoftwareMonkeys.WorkHub.Data.Tests
{
	/// <summary>
	/// Description of FilterTests.
	/// </summary>
	[TestFixture]
	public class FilterTests : BaseDataTestFixture
	{
		public FilterTests()
		{
		}
		
		
		[Test]
		public void Test_FilterGroup_Or()
		{
			using (LogGroup logGroup = LogGroup.Start("Testing a filter group query with the OR operator.", NLog.LogLevel.Debug))
			{
				TestEntity e1 = new TestEntity();
				e1.Name = "Test E1";
				
				FilterGroup filterGroup = new FilterGroup();
				filterGroup.Operator = FilterGroupOperator.Or;
				
				PropertyFilter filter1 = (PropertyFilter)DataAccess.Data.CreateFilter(typeof(PropertyFilter));
				filter1.PropertyName = "Name";
				filter1.PropertyValue = e1.Name;
				filter1.AddType(typeof(TestEntity));
				
				PropertyFilter filter2 = (PropertyFilter)DataAccess.Data.CreateFilter(typeof(PropertyFilter));
				filter2.PropertyName = "Name";
				filter2.PropertyValue = "Another value";
				filter2.AddType(typeof(TestEntity));
				
				filterGroup.Filters = new BaseFilter[] {filter1, filter2};
				
				DataAccess.Data.Stores[typeof(TestEntity)].Saver.Save(e1);
				
				IEntity[] found = (IEntity[])DataAccess.Data.Indexer.GetEntities(filterGroup);
				
				Assert.IsNotNull(found, "Null value returned.");
				
				if (found != null)
					Assert.IsTrue(found.Length > 0, "No results found.");
				
				
				DataAccess.Data.Deleter.Delete(e1);
			}
		}

		[Test]
		public void Test_FilterGroup_And_Exclusion()
		{
			using (LogGroup logGroup = LogGroup.Start("Testing a filter group query with the AND operator.", NLog.LogLevel.Debug))
			{
				TestEntity e1 = new TestEntity();
				e1.Name = "Test E1";
				
				FilterGroup filterGroup = new FilterGroup();
				filterGroup.Operator = FilterGroupOperator.And;
				
				PropertyFilter filter1 = (PropertyFilter)DataAccess.Data.CreateFilter(typeof(PropertyFilter));
				filter1.PropertyName = "Name";
				filter1.PropertyValue = e1.Name;
				filter1.AddType(typeof(TestEntity));
				
				PropertyFilter filter2 = (PropertyFilter)DataAccess.Data.CreateFilter(typeof(PropertyFilter));
				filter2.PropertyName = "Name";
				filter2.PropertyValue = "Another value";
				filter2.AddType(typeof(TestEntity));
				
				filterGroup.Filters = new BaseFilter[] {filter1, filter2};
				
				DataAccess.Data.Saver.Save(e1);
				
				IEntity[] found = (IEntity[])DataAccess.Data.Indexer.GetEntities(filterGroup);
				
				Assert.IsNotNull(found, "Null array returned.");
				
				Collection<TestEntity> foundList = new Collection<TestEntity>(found);
				
				if (found != null)
					Assert.AreEqual(0, foundList.Count, "Entity retrieved when it shouldn't have matched.");
				
				
				DataAccess.Data.Deleter.Delete(e1);
			}
		}

	}
}
