//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareMonkeys.WorkHub.Modules.Voting.Properties {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Language {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		public Language() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftwareMonkeys.WorkHub.Modules.Voting.Properties.Language", typeof(Language).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to All Votes.
		/// </summary>
		public static string AllVotes {
			get {
				return ResourceManager.GetString("AllVotes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to (asc).
		/// </summary>
		public static string Asc {
			get {
				return ResourceManager.GetString("Asc", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Are you sure you want to cancel creating this link?.
		/// </summary>
		public static string ConfirmCancelCreateVote {
			get {
				return ResourceManager.GetString("ConfirmCancelCreateVote", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Are you sure you wish to delete this link?.
		/// </summary>
		public static string ConfirmDeleteVote {
			get {
				return ResourceManager.GetString("ConfirmDeleteVote", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Create Vote.
		/// </summary>
		public static string CreateVote {
			get {
				return ResourceManager.GetString("CreateVote", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Enter the new link details in the form below..
		/// </summary>
		public static string CreateVoteIntro {
			get {
				return ResourceManager.GetString("CreateVoteIntro", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Delete.
		/// </summary>
		public static string Delete {
			get {
				return ResourceManager.GetString("Delete", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Delete this link.
		/// </summary>
		public static string DeleteVoteToolTip {
			get {
				return ResourceManager.GetString("DeleteVoteToolTip", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to (desc).
		/// </summary>
		public static string Desc {
			get {
				return ResourceManager.GetString("Desc", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Edit.
		/// </summary>
		public static string Edit {
			get {
				return ResourceManager.GetString("Edit", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Edit Vote.
		/// </summary>
		public static string EditVote {
			get {
				return ResourceManager.GetString("EditVote", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Edit the link details in the form below..
		/// </summary>
		public static string EditVoteIntro {
			get {
				return ResourceManager.GetString("EditVoteIntro", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Edit this link.
		/// </summary>
		public static string EditVoteToolTip {
			get {
				return ResourceManager.GetString("EditVoteToolTip", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ID.
		/// </summary>
		public static string ID {
			get {
				return ResourceManager.GetString("ID", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Manage Votes.
		/// </summary>
		public static string ManageVotes {
			get {
				return ResourceManager.GetString("ManageVotes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Create and manage links in the index below..
		/// </summary>
		public static string ManageVotesIntro {
			get {
				return ResourceManager.GetString("ManageVotesIntro", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to N/A.
		/// </summary>
		public static string NA {
			get {
				return ResourceManager.GetString("NA", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Your negative vote has been recorded..
		/// </summary>
		public static string NegativeVoteRecorded {
			get {
				return ResourceManager.GetString("NegativeVoteRecorded", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to New Vote Details.
		/// </summary>
		public static string NewVoteDetails {
			get {
				return ResourceManager.GetString("NewVoteDetails", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No summary has been provided for this link..
		/// </summary>
		public static string NoSummary {
			get {
				return ResourceManager.GetString("NoSummary", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No topics have been associated with this link..
		/// </summary>
		public static string NoTopicsForVote {
			get {
				return ResourceManager.GetString("NoTopicsForVote", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No links found..
		/// </summary>
		public static string NoVotes {
			get {
				return ResourceManager.GetString("NoVotes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Your positive vote has been recorded..
		/// </summary>
		public static string PositiveVoteRecorded {
			get {
				return ResourceManager.GetString("PositiveVoteRecorded", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Project.
		/// </summary>
		public static string Project {
			get {
				return ResourceManager.GetString("Project", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Projects.
		/// </summary>
		public static string Projects {
			get {
				return ResourceManager.GetString("Projects", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Resources.
		/// </summary>
		public static string Resources {
			get {
				return ResourceManager.GetString("Resources", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Save.
		/// </summary>
		public static string Save {
			get {
				return ResourceManager.GetString("Save", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Select Project.
		/// </summary>
		public static string SelectProject {
			get {
				return ResourceManager.GetString("SelectProject", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Summary.
		/// </summary>
		public static string Summary {
			get {
				return ResourceManager.GetString("Summary", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Title.
		/// </summary>
		public static string Title {
			get {
				return ResourceManager.GetString("Title", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Topic.
		/// </summary>
		public static string Topic {
			get {
				return ResourceManager.GetString("Topic", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Topics.
		/// </summary>
		public static string Topics {
			get {
				return ResourceManager.GetString("Topics", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Update.
		/// </summary>
		public static string Update {
			get {
				return ResourceManager.GetString("Update", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to URL.
		/// </summary>
		public static string Url {
			get {
				return ResourceManager.GetString("Url", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to View.
		/// </summary>
		public static string View {
			get {
				return ResourceManager.GetString("View", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Vote.
		/// </summary>
		public static string Vote {
			get {
				return ResourceManager.GetString("Vote", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The selected link was deleted successfully..
		/// </summary>
		public static string VoteDeleted {
			get {
				return ResourceManager.GetString("VoteDeleted", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Vote Details.
		/// </summary>
		public static string VoteDetails {
			get {
				return ResourceManager.GetString("VoteDetails", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Please select at least one project that this link is assigned to..
		/// </summary>
		public static string VoteProjectRequired {
			get {
				return ResourceManager.GetString("VoteProjectRequired", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Votes.
		/// </summary>
		public static string Votes {
			get {
				return ResourceManager.GetString("Votes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The link was saved successfully..
		/// </summary>
		public static string VoteSaved {
			get {
				return ResourceManager.GetString("VoteSaved", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Vote Summary.
		/// </summary>
		public static string VoteSummary {
			get {
				return ResourceManager.GetString("VoteSummary", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Votes XML.
		/// </summary>
		public static string VotesXml {
			get {
				return ResourceManager.GetString("VotesXml", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The links below display links in XML format..
		/// </summary>
		public static string VotesXmlIntro {
			get {
				return ResourceManager.GetString("VotesXmlIntro", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Votes XML Pages.
		/// </summary>
		public static string VotesXmlPages {
			get {
				return ResourceManager.GetString("VotesXmlPages", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to A total of ${TotalVotes} votes have been made..
		/// </summary>
		public static string VoteTitlePopup {
			get {
				return ResourceManager.GetString("VoteTitlePopup", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Please enter a title for this link..
		/// </summary>
		public static string VoteTitleRequired {
			get {
				return ResourceManager.GetString("VoteTitleRequired", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The title of the link is in use, please try a different one..
		/// </summary>
		public static string VoteTitleTaken {
			get {
				return ResourceManager.GetString("VoteTitleTaken", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The link was updated successfully..
		/// </summary>
		public static string VoteUpdated {
			get {
				return ResourceManager.GetString("VoteUpdated", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Please enter a URL for the link..
		/// </summary>
		public static string VoteUrlRequired {
			get {
				return ResourceManager.GetString("VoteUrlRequired", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to XML.
		/// </summary>
		public static string Xml {
			get {
				return ResourceManager.GetString("Xml", resourceCulture);
			}
		}
	}
}
