/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business\Security\AuthoriseDeleteAuthoredEntityStrategy.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Business;
using SoftwareMonkeys.WorkHub.Business.Security;
using SoftwareMonkeys.WorkHub.Entities;

namespace SoftwareMonkeys.WorkHub.Business.Security
{
	/// <summary>
	/// 
	/// </summary>
	[AuthoriseStrategy("Delete", "IAuthored")]
	public class AuthoriseDeleteAuthoredEntityStrategy : BaseAuthoriseStrategy, IAuthoriseDeleteStrategy
	{
		public AuthoriseDeleteAuthoredEntityStrategy()
		{
		}
		
		public override bool IsAuthorised(SoftwareMonkeys.WorkHub.Entities.IEntity entity)
		{
			IAuthored authoredEntity = (IAuthored)entity;
			
			// If the user is an administrator they are authorised
			if (AuthenticationState.UserIsInRole("Administrator"))
				return true;
			
			// If the current user is the author
			if (UserIsAuthor((IAuthored)entity))
				return true;
			else
				// otherwise NOT authorised
				return false;
		}
		
		
		protected virtual bool UserIsAuthor(IAuthored entity)
		{
			ActivateStrategy.New(entity).Activate(entity, "Author");
			
			// If the current use is authenticated
			return AuthenticationState.IsAuthenticated
				// and if the current user is the author
				&& entity.Author != null
				&& AuthenticationState.User != null
				&& entity.Author.ID == AuthenticationState.User.ID;
		}
		
		public override bool IsAuthorised(string shortTypeName)
		{
			return AuthenticationState.IsAuthenticated;
		}
	}
}
