/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business\Security\AuthoriseRetrieveAuthoredEntityStrategy.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Entities;

namespace SoftwareMonkeys.WorkHub.Business.Security
{
	/// <summary>
	///
	/// </summary>
	[AuthoriseStrategy("Retrieve", "IAuthored")]
	public class AuthoriseRetrieveAuthoredEntityStrategy : AuthoriseRetrieveStrategy
	{
		public AuthoriseRetrieveAuthoredEntityStrategy()
		{
		}
		
		public override bool IsAuthorised(SoftwareMonkeys.WorkHub.Entities.IEntity entity)
		{
			if (!AuthenticationState.IsAuthenticated)
				return false;
			
			IAuthored authoredEntity = (IAuthored)entity;
			
			ActivateStrategy.New(authoredEntity).Activate(authoredEntity, "Author");
			
			return authoredEntity.IsPublic
				|| (authoredEntity != null && authoredEntity.Author.ID == AuthenticationState.User.ID);
		}
	}
}
