/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business\Security\AuthoriseUpdateProjectionStrategy.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Business;
using SoftwareMonkeys.WorkHub.Entities;

namespace SoftwareMonkeys.WorkHub.Business.Security
{
	/// <summary>
	/// 
	/// </summary>
	[Strategy("AuthoriseUpdate", "Projection")]
	public class AuthoriseUpdateProjectionStrategy : BaseAuthoriseStrategy
	{
		/// <summary>
		/// Checks whether the current user is authorised to delete an entity of the specified type.
		/// </summary>
		/// <param name="shortTypeName">The type of entity being deleted.</param>
		/// <returns>A value indicating whether the current user is authorised to delete an entity of the specified type.</returns>
		public override bool IsAuthorised(string shortTypeName)
		{
			if (!RequireAuthorisation)
				return true;
			
			return AuthenticationState.UserIsInRole("Administrator");
		}
		
		/// <summary>
		/// Checks whether the current user is authorised to delete the provided entity.
		/// </summary>
		/// <param name="shortTypeName">The type of entity being deleted.</param>
		/// <returns>A value indicating whether the current user is authorised to delete the provided entity.</returns>
		public override bool IsAuthorised(IEntity entity)
		{
			if (!RequireAuthorisation)
				return true;
			
			return AuthenticationState.UserIsInRole("Administrator");
		}
		
		public AuthoriseUpdateProjectionStrategy()
		{
		}
	}
}
