/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business\Security\AuthoriseStrategyAttribute.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;

namespace SoftwareMonkeys.WorkHub.Business.Security
{
	/// <summary>
	/// 
	/// </summary>
	public class AuthoriseStrategyAttribute : StrategyAttribute
	{
		private string restrictedAction;
		/// <summary>
		/// Gets/sets the name of the action being restricted.
		/// </summary>
		public string RestrictedAction
		{
			get { return restrictedAction; }
			set { restrictedAction = value; }
		}
		
		public AuthoriseStrategyAttribute(string restrictedAction, string typeName) : base("Authorise" + restrictedAction, typeName)
		{
			RestrictedAction = restrictedAction;
		}
		
		public AuthoriseStrategyAttribute()
		{}
	}
}
