/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business\Security\UnauthorisedException.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Entities;

namespace SoftwareMonkeys.WorkHub.Business.Security
{
	/// <summary>
	/// Thrown when an operation is attemped without authorisation.
	/// </summary>
	[Serializable]
	public class UnauthorisedException : Exception
	{
		public UnauthorisedException(string action, string shortTypeName) : base("The current user is not authorised to perform the action '" + action + "' with an entity of type '" + shortTypeName + "'.")
		{}
		
		public UnauthorisedException(string action, IEntity entity) : base("The current user is not authorised to perform the action '" + action + "' with an entity of type '" + entity.ShortTypeName + "' and ID '" + entity.ID.ToString() + "'.")
		{}
	}
}
