/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web.Tests\MockControlLoader.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Tests;
using System.Web.UI;

namespace SoftwareMonkeys.WorkHub.Web.Tests
{
	/// <summary>
	/// 
	/// </summary>
	public class MockControlLoader : ControlLoader
	{
		private BaseTestFixture fixture;
		public BaseTestFixture Fixture
		{
			get { return fixture; }
			set { fixture = value; }
		}
		
		private string mockControlFilePath;
		/// <summary>
		/// The path of the mock control.
		/// </summary>
		public string MockControlFilePath
		{
			get { return mockControlFilePath;  }
			set { mockControlFilePath = value; }
		}
		
		public override string ApplicationPath
		{
			get { return TestUtilities.GetTestApplicationPath(Fixture, "MockApplication"); }
			set { base.ApplicationPath = value; }
		}
		
		public MockControlLoader(BaseTestFixture fixture) : base(null)
		{
			Fixture = fixture;
		}
		
		public MockControlLoader(BaseTestFixture fixture, string mockControlFilePath) : base(null)
		{
			MockControlFilePath = mockControlFilePath;
			Fixture = fixture;
		}
		
		public override System.Web.UI.Control LoadControl(string virtualPath)
		{
			return new MockUserControl();
		}
	}
}
