/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\AutoBackupChecker.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Configuration;
using SoftwareMonkeys.WorkHub.Configuration;
using SoftwareMonkeys.WorkHub.State;

namespace SoftwareMonkeys.WorkHub.Web
{
	/// <summary>
	///
	/// </summary>
	public class AutoBackupChecker
	{
		static private AutoBackupChecker current;
		static public AutoBackupChecker Current
		{
			get {
				if (current == null)
					current = new AutoBackupChecker();
				return current; }
		}
		
		public bool GetEnableAuto()
		{
			if (ConfigurationSettings.AppSettings["Backup.EnableAuto"] != null)
				return Convert.ToBoolean(ConfigurationSettings.AppSettings["Backup.EnableAuto"]);
			else
				return false;
		}

		public bool AutoBackupDue()
		{
			if (!GetEnableAuto())
				return false;
			
			DateTime lastAutoBackup = GetLastAutoBackup();
			int autoInterval = GetAutoInterval();
			// true if DateTime.Now is greater than last backup + interval
			return (DateTime.Now > lastAutoBackup.AddHours(autoInterval));
		}

		public DateTime GetLastAutoBackup()
		{
			if (StateAccess.IsInitialized
			    && StateAccess.State.ContainsApplication("LastAutoBackup"))
			{
				return (DateTime)StateAccess.State.GetApplication("LastAutoBackup");
			}
			else
			{
				return DateTime.Now;
			}
		}

		public int GetAutoInterval()
		{
			if (Config.IsInitialized
			    && ConfigurationSettings.AppSettings["Backup.AutoInterval"] != null)
			{
				return Int32.Parse(ConfigurationSettings.AppSettings["Backup.AutoInterval"]);
			}
			else
				return 24;
		}
	}
}
