/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\AutoBackupInitializer.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Configuration;
using System.Net;
using System.Web;
using SoftwareMonkeys.WorkHub.Diagnostics;
using SoftwareMonkeys.WorkHub.Business;
using SoftwareMonkeys.WorkHub.Configuration;
using SoftwareMonkeys.WorkHub.Web.Properties;

namespace SoftwareMonkeys.WorkHub.Web
{
	/// <summary>
	/// 
	/// </summary>
	public class AutoBackupInitializer
	{
		public AutoBackupInitializer()
		{
		}
		
		public void Initialize()
		{
			if (new AutoBackupChecker().AutoBackupDue())
			{
				// Extend the timeout to ensure there is no timeout error
				using (TimeoutExtender extender = TimeoutExtender.NewMinutes(60))
				{
					try
					{
						LaunchBackup();
					}
					catch (Exception ex)
					{
						LogWriter.Error(new Exception("An error occurred during the automatic backup.", ex));
					}
				}
			}
		}
		
		void LaunchBackup()
		{
			using (LogGroup logGroup = LogGroup.StartDebug("Launching backup."))
			{
				if (Config.IsInitialized)
				{
					string url = new UrlConverter().ToAbsolute(HttpContext.Current.Request.ApplicationPath + "/AutoBackup.aspx");
					
					HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
					
					request.Method = "GET";
					
					IAsyncResult result = request.BeginGetResponse(null, null);
				}
				else
				{
					LogWriter.Debug("!Config.IsInitialized - Skipping backup.");
				}
			}
		}
	}
}
