/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Web\UrlRewriter.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Web;
using SoftwareMonkeys.WorkHub.State;
using SoftwareMonkeys.WorkHub.Web.Projections;
using SoftwareMonkeys.WorkHub.Diagnostics;

namespace SoftwareMonkeys.WorkHub.Web
{
	/// <summary>
	/// 
	/// </summary>
	public class UrlRewriter
	{
		public static void Initialize()
		{
			using (LogGroup logGroup = LogGroup.StartDebug("Initializing the URL rewriter."))
			{
				
				if (StateAccess.IsInitialized && ProjectionState.IsInitialized)
				{
					string url = new ProjectionMapper().GetInternalPath(HttpContext.Current.Request.Url.ToString());
					
					HttpContext.Current.Items["OriginalUrl"] = HttpContext.Current.Request.Url.ToString();
					
					if (url != null && url != String.Empty)
					{
						//HttpContext.Current.Server.Execute(url, true);
						HttpContext.Current.RewritePath(url, false); // Pass false parameter to ensure the form post back path is correct.
					}
				}
				else
					new SetupChecker().Check();
			}
		}
	}
}
