/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Diagnostics\CorruptLogException.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;

namespace SoftwareMonkeys.WorkHub.Diagnostics
{
	/// <summary>
	/// Description of CorruptLogException.
	/// </summary>
	public class CorruptLogException : Exception
	{
		public CorruptLogException(LogGroup group) : base("The log has been corrupted while in memory.\n"
		                                                  + "Group ID: " + group.ID.ToString() + "\n"
		                                                  + "Parent ID: " + group.ParentID.ToString() + "\n"
		                                                  + "Summary: " + group.Summary + "\n"
		                                                  + "Current group ID: " + DiagnosticState.CurrentGroupID.ToString() + "\n"
		                                                )
		{
			
		}
	}
}
