/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business.Tests\Security\AuthoriseReferenceMockPublicEntityStrategy.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Reflection;
using SoftwareMonkeys.WorkHub.Business.Security;
using SoftwareMonkeys.WorkHub.Entities;
using SoftwareMonkeys.WorkHub.Entities.Tests.Entities;

namespace SoftwareMonkeys.WorkHub.Business.Tests.Security
{
	/// <summary>
	/// 
	/// </summary>
	[AuthoriseReferenceStrategy("MockEntity", "PublicEntities", "MockPublicEntity")]
	public class AuthoriseReferenceMockPublicEntityStrategy : AuthoriseReferenceStrategy
	{
				
		public override bool IsAuthorised(SoftwareMonkeys.WorkHub.Entities.IEntity entity)
		{
			return true;
		}
		
		public override bool IsAuthorised(string shortTypeName)
		{
			return true;
		}
	}
}
