/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Business.Tests\Security\AuthoriseReferenceMockRestrictedEntityStrategy.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Reflection;
using SoftwareMonkeys.WorkHub.Business.Security;
using SoftwareMonkeys.WorkHub.Entities;
using SoftwareMonkeys.WorkHub.Entities.Tests.Entities;

namespace SoftwareMonkeys.WorkHub.Business.Tests.Security
{
	/// <summary>
	/// 
	/// </summary>
	[AuthoriseReferenceStrategy("MockEntity", "RestrictedEntities", "MockRestrictedEntity")]
	public class AuthoriseReferenceMockRestrictedEntityStrategy : AuthoriseReferenceStrategy
	{
		public override bool IsAuthorised()
		{
			return false;
		}
		
		public override bool IsAuthorised(IEntity entity)
		{
			return false;
		}
		
		public override bool IsAuthorised(string shortTypeName)
		{
			return false;
		}
	}
}
