/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Contracts\Business\Security\IAuthoriseIndexStrategy.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Entities;

namespace SoftwareMonkeys.WorkHub.Business.Security
{
	/// <summary>
	/// Defines the interface of all authorise index strategies.
	/// </summary>
	public interface IAuthoriseIndexStrategy : IAuthoriseStrategy
	{
		/// <summary>
		/// Checks whether the current user is authorised to index the provided entities.
		/// </summary>
		/// <param name="entities">The entities being indexed.</param>
		/// <returns>The authorised entities. (Or empty if none are authorised)</returns>
		IEntity[] Authorise(IEntity[] entities);
		
		/// <summary>
		/// Ensures that the current user is authorised to access an index of entities including the one provided.
		/// </summary>
		/// <param name="entities">The entities in the index.</param>
		void EnsureAuthorised(ref IEntity[] entities);
		
		/// <summary>
		/// Ensures that the current user is authorised to access an index of entities including the one provided.
		/// </summary>
		/// <param name="entities">The entities in the index.</param>
		void EnsureAuthorised<T>(ref T[] entities)
			where T : IEntity;
	}
}
