/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Contracts\Business\Security\IAuthoriseReferenceStrategy.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Reflection;
using SoftwareMonkeys.WorkHub.Entities;

namespace SoftwareMonkeys.WorkHub.Business.Security
{
	/// <summary>
	/// 
	/// </summary>
	public interface IAuthoriseReferenceStrategy : IAuthoriseStrategy
	{
		IEntity SourceEntity { get;set; }
		string SourceProperty { get;set; }
		
		/// <summary>
		/// Authorises the reference on the source property of the source entity.
		/// </summary>
		void Authorise();
		
		IEntity[] Authorise(IEntity[] toEntities);
	}
}
