/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Data.Db4o\Db4oPropertyFilter.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Collections;
using Db4objects.Db4o.Query;
using SoftwareMonkeys.WorkHub.Diagnostics;
using SoftwareMonkeys.WorkHub.Entities;
using System.Reflection;

namespace SoftwareMonkeys.WorkHub.Data.Db4o
{
    /// <summary>
    /// Represents a data filter based on a specific entity field.
    /// </summary>
    public class Db4oPropertyFilter : PropertyFilter
    {
    	// Use the base implementation
    }

}
