/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Data.Db4o\Db4oDataStoreFactory.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using System.IO;
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using Db4objects.Db4o;
using Db4objects.Db4o.Query;
using Db4objects.Db4o.Ext;
using System.Reflection;
using SoftwareMonkeys.WorkHub;
using SoftwareMonkeys.WorkHub.Entities;
using SoftwareMonkeys.WorkHub.Configuration;
using SoftwareMonkeys.WorkHub.Diagnostics;
using Db4objects.Db4o.Config;

namespace SoftwareMonkeys.WorkHub.Data.Db4o
{
	/// <summary>
	/// Used to create new data stores.
	/// </summary>
	public static class Db4oDataStoreFactory
	{
		static public Db4oDataStore InitializeDataStore(string dataStoreName)
		{
			return InitializeDataStore(dataStoreName, Db4oFactory.NewConfiguration());
		}
		
		/// <summary>
		/// Initializes the data store.
		/// </summary>
		static public Db4oDataStore InitializeDataStore(string dataStoreName, IConfiguration db4oConfiguration)
		{
			Db4oDataStore store = null;

			using (LogGroup logGroup = LogGroup.StartDebug("Initializing data store: " + dataStoreName))
			{
				if (!Config.IsInitialized)
					throw new InvalidOperationException("The application config file is not present. Run the setup process and try again.");
				
				LogWriter.Debug("Creating new data store: " + dataStoreName);
				
				// Create a new data store
				store = new Db4oDataStore(db4oConfiguration);
				store.Name = dataStoreName;

				store.Open();
			}
			return store;
			
		}
	}
}