/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Data.Db4o\MatchFilterGroupPredicate.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using Db4objects.Db4o.Query;
using SoftwareMonkeys.WorkHub.Entities;

namespace SoftwareMonkeys.WorkHub.Data.Db4o
{
	/// <summary>
	/// 
	/// </summary>
	public class MatchFilterGroupPredicate : Predicate
	{
		IDataFilterGroup FilterGroup = null;
		
		public MatchFilterGroupPredicate(IDataFilterGroup filterGroup)
		{
			FilterGroup = filterGroup;
		}
		
		public bool Match(IEntity entity)
		{
			bool doesMatch = true;
			
			//using (LogGroup logGroup2 = LogGroup.Start("Querying entity.", NLog.LogLevel.Debug))
			//{

			//LogWriter.Debug("Checking type " + e.GetType().ToString());
			//LogWriter.Debug("Entity ID: " + e.ID);
			
			doesMatch = FilterGroup.IsMatch(entity);
			
			//LogWriter.Debug("Matches: " + matches);
			//}
			return doesMatch;
		}
	}
}
