/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Diagnostics.Tests\MockModeDetector.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;
using SoftwareMonkeys.WorkHub.Diagnostics;

namespace SoftwareMonkeys.WorkHub.Diagnostics.Tests
{
	/// <summary>
	/// 
	/// </summary>
	public class MockModeDetector : ModeDetector
	{
		private bool isDebug = false;
		
		public override bool IsDebug {
			get { return isDebug; }
		}
		
		public MockModeDetector(bool isDebug)
		{
			this.isDebug = isDebug;
		}
		
	}
}
