/*

====================================================================================================

This file as been imported by the Commander console and the 'Import files' script.

The source of the import is:
C:\Projects\SoftwareMonkeys\SiteStarter\Src\App\SoftwareMonkeys.SiteStarter.Contracts\Business\ICommandInfo.cs

Do not edit this file or changes may be lost. Edit the source file and the changes will be imported by all projects that use it.

====================================================================================================


*/

using System;

namespace SoftwareMonkeys.WorkHub.Business
{
	/// <summary>
	/// 
	/// </summary>
	public interface ICommandInfo
	{
		/// <summary>
		/// The primary action.
		/// </summary>
		string Action {get;set;}
		
		/// <summary>
		/// The type involved in the action.
		/// </summary>
		string TypeName {get;set;}
		
		/// <summary>
		/// Alternative terms for the action.
		/// </summary>
		string[] AliasActions {get;set;}
		
		/// <summary>
		/// All actions including primary and aliases.
		/// </summary>
		string[] AllActions {get;}
	}
}
